components/kcp/api/cloud-resources/v1beta1/iprange_types.go
components/kcp/api/cloud-resources/v1beta1/nfsinstance_types.go
components/kcp/api/cloud-resources/v1beta1/scope_types.go
components/kcp/api/cloud-resources/v1beta1/vpcpeering_types.go
components/kcp/config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
components/kcp/config/crd/bases/cloud-resources.kyma-project.io_scopes.yaml
components/kcp/go.mod
components/kcp/go.sum
components/kcp/pkg/common/actions/focal/types.go
components/kcp/pkg/common/actions/new.go
components/kcp/pkg/common/actions/scope/createScope.go
components/kcp/pkg/common/actions/scope/createScopeAzure.go
components/kcp/pkg/common/actions/scope/createScopeGcp.go
components/kcp/pkg/common/actions/scope/ensureScopeCommonFields.go
components/kcp/pkg/common/actions/scope/findScope.go
components/kcp/pkg/common/actions/scope/new.go
components/kcp/pkg/common/actions/scope/updateScopeRef.go
components/kcp/pkg/common/actions/scope/whenNoScopeCreated.go
components/kcp/pkg/common/actions/scope/whenNoScopeRef.go
components/kcp/pkg/iprange/reconciler.go
components/kcp/pkg/provider/aws/iprange/state.go
components/lib/composed/action.go
components/lib/composed/errors.go
components/lib/composed/predicate.go

- fixed Scope flow to find existing Scope when scoreRef is missing

Fix scope flow to find existing scope

---

components/kcp/api/cloud-control/v1beta1/types.go
components/kcp/cmd/main.go
components/kcp/pkg/common/actions/focal/addFinalizer.go
components/kcp/pkg/common/actions/focal/removeFinalizer.go
components/kcp/pkg/iprange/reconciler.go
components/kcp/pkg/provider/gcp/client/gcpConstants.go
components/kcp/pkg/provider/gcp/client/provider.go
components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
components/kcp/pkg/provider/gcp/iprange/compareStates.go
components/kcp/pkg/provider/gcp/iprange/loadAddress.go
components/kcp/pkg/provider/gcp/iprange/new.go
components/kcp/pkg/provider/gcp/iprange/state.go
components/kcp/pkg/provider/gcp/iprange/switchToReadyState.go
components/kcp/pkg/provider/gcp/iprange/validateCidr.go
components/kcp/pkg/util/cidr.go

GCP IPRange GetAddress call to GCP
NA

GCP IPRange GetAddress call to GCP

---

components/kcp/api/cloud-resources/v1beta1/condition.go
components/kcp/cmd/main.go
components/kcp/pkg/criprange/createKcpIpRange.go
components/kcp/pkg/criprange/new.go
components/kcp/pkg/criprange/reconciler.go
components/kcp/pkg/criprange/updateStatus.go
components/lib/composed/action_test.go
components/lib/composed/state.go
components/lib/composed/updateStatus.go

- added update status for the SKR IpRange
- added SKR IpRange Reconciler
- refactored `composed.NewStateFactory(client, eventRecorder, scheme)` into `composed.NewStateFactory(stateCluster)`

(Sync) IpRange SKR reconciliation

---

components/kcp/pkg/common/actions/addFinalizer.go
components/kcp/pkg/common/actions/focal/types.go
components/kcp/pkg/common/actions/removeFinalizer.go
components/kcp/pkg/provider/gcp/client/gcpConstants.go
components/kcp/pkg/provider/gcp/iprange/compareStates.go
components/kcp/pkg/provider/gcp/iprange/new.go
components/kcp/pkg/provider/gcp/iprange/state.go
components/kcp/pkg/provider/gcp/iprange/syncAddress.go
components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
components/kcp/pkg/provider/gcp/nfsinstance/checkNUpdateState.go
components/kcp/pkg/provider/gcp/nfsinstance/checkUpdateMask.go
components/kcp/pkg/provider/gcp/nfsinstance/new.go
components/kcp/pkg/provider/gcp/nfsinstance/state.go
components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go

Removed Add/Remove Finalizers actions from focal package
NA

Removed Add/Remove Finalizers actions from focal package

---

components/kcp/api/cloud-resources/v1beta1/gcpnfsvolume_types.go
components/kcp/config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
components/kcp/pkg/skr/nfs/crgcpnfsvolume/deletePersistenceVolume.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/loadPersistenceVolume.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/modifyKcpNfsInstance.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/modifyPersistenceVolume.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/reconciler.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/removePersistenceVolumeFinalizer.go
components/kcp/pkg/skr/nfs/crgcpnfsvolume/validateSpec.go

**Adding actions for gcpNfsVolume**
- adding reconciler actions for gcpNfsVolume with no implementation
https://jira.tools.sap/browse/PHX-37

Identifying and adding actions for gcpNfsVolume

---

Makefile
PROJECT
api/cloud-control/v1beta1/providerType.go
internal/controller/cloud-control/scope.yaml
internal/controller/cloud-control/scope_aws_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/aws/mock/scopeStore.go
pkg/testinfra/dsl.go
pkg/testinfra/run.go

Scope AWS integration test

---

Dockerfile

Dockerfile z

---

pkg/skr/nfs/crgcpnfsvolume/createPersistenceVolume.go
pkg/skr/nfs/crgcpnfsvolume/deletePersistenceVolume.go
pkg/skr/nfs/crgcpnfsvolume/loadKcpNfsInstance.go
pkg/skr/nfs/crgcpnfsvolume/loadPersistenceVolume.go
pkg/skr/nfs/crgcpnfsvolume/modifyPersistenceVolume.go
pkg/skr/nfs/crgcpnfsvolume/reconciler.go
pkg/skr/nfs/crgcpnfsvolume/removePersistenceVolumeFinalizer.go
pkg/skr/nfs/crgcpnfsvolume/state.go

GcpNfsVolume Reconciler PV actions
https://jira.tools.sap/browse/PHX-39

GcpNfsVolume Reconciler PV actions

---

pkg/skr/iprange/addFinalizer.go
pkg/skr/iprange/copyCidrToStatus.go
pkg/skr/iprange/createKcpIpRange.go
pkg/skr/iprange/deleteKcpIpRange.go
pkg/skr/iprange/loadKcpIpRange.go
pkg/skr/iprange/preventCidrChange.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/removeFinalizer.go
pkg/skr/iprange/state.go
pkg/skr/iprange/updateStatus.go
pkg/skr/iprange/validateCidr.go

- `git mv pkg/skr/iprange/cripange/* pkg/skr/iprange`

fix package paths in pkg/skr/iprange

---

api/cloud-control/v1beta1/iprange_types.go
cmd/main.go
internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/suite_test.go
pkg/common/ignorant/store.go
pkg/kcp/iprange/ignorant.go
pkg/kcp/iprange/reconciler.go
pkg/kcp/provider/aws/iprange/createSubnets.go
pkg/kcp/provider/aws/iprange/findCloudResourceSubnets.go
pkg/kcp/provider/aws/iprange/new.go
pkg/kcp/provider/aws/iprange/preventCidrEdit.go
pkg/kcp/provider/aws/mock/vpcStore.go
pkg/kcp/provider/aws/util/ec2tags.go
pkg/kcp/scope/ignorant.go
pkg/kcp/scope/reconciler.go
pkg/testinfra/dsl.go
pkg/testinfra/types.go

IpRange AWS test

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
pkg/composed/updateStatus.go
pkg/skr/gcpnfsvolume/createPersistenceVolume.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/updateStatus.go
pkg/skr/gcpnfsvolume/validateSpec.go

- Updating gcpNfsVolume conditions and reasons
- adding capacity to status to show what capacity "ready" condition is referring to
- few small fixes based on manual integration test
https://jira.tools.sap/browse/PHX-42

Updating gcpNfsVolume conditions and reasons

---

internal/controller/cloud-resources/gcpnfsvolume_controller.go
pkg/skr/gcpnfsvolume/createPersistenceVolume.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
pkg/skr/gcpnfsvolume/pvEventHandler.go
pkg/skr/gcpnfsvolume/state.go
pkg/skr/runtime/registry/builder.go

GcpNfs Reconciler PV related fixes.

GcpNfs PV fixes

---

sec-scanners-config.yaml

- Security scanners configuration

Adding security scanners configuration

---

internal/controller/cloud-control/iprange_gcp_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/gcp/client/provider.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
pkg/kcp/provider/gcp/iprange/client/computeClient.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
pkg/kcp/provider/gcp/iprange/state.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection.go
pkg/kcp/provider/gcp/iprange/updateState.go
pkg/kcp/provider/gcp/mock/ctx.go
pkg/kcp/provider/gcp/mock/iprangeStore.go
pkg/kcp/provider/gcp/mock/nfsStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/kcp/provider/gcp/nfsinstance/state.go
pkg/testinfra/dsl.go
pkg/testinfra/env.go
pkg/testinfra/run.go
pkg/testinfra/types.go

- Added integration test for GCP IP Range in Kcp
- Moved all the GCP access logic into the Client Provider code
- Created Mocks for the IpRange GCP client interfaces.

GCP IPRange Integration Test

---

pkg/common/actions/focal/state.go
pkg/composed/updateStatus.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
pkg/kcp/provider/gcp/iprange/loadAddress.go
pkg/kcp/provider/gcp/iprange/loadPsaConnection.go
pkg/kcp/provider/gcp/iprange/syncAddress.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection.go
pkg/kcp/provider/gcp/iprange/updateState.go
pkg/kcp/provider/gcp/iprange/validateCidr.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/new.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/validateAlways.go
pkg/kcp/provider/gcp/nfsinstance/validatePostCreate.go

Refactored GCP logic in KCP to use UpdateStatus builder. 
https://jira.tools.sap/projects/PHX/issues/PHX-46

GCP NFS - Refactor to use UpdateStatus builder

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/labels.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
internal/controller/cloud-resources/gcpnfsvolume_test.go
internal/controller/cloud-resources/suite_test.go
pkg/skr/gcpnfsvolume/createPersistenceVolume.go
pkg/skr/gcpnfsvolume/loadKcpNfsInstance.go
pkg/skr/gcpnfsvolume/loadPersistenceVolume.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/pvEventHandler.go
pkg/testinfra/dsl/gcpNfsVolume.go
pkg/testinfra/dsl/kcpIpRange.go
pkg/testinfra/dsl/objActions.go

GCP NFS - SKR Reconciler tests

GCP NFS - SKR Reconciler test

---

internal/controller/cloud-control/nfsinstance_gcp_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/gcp/mock/nfsStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/testinfra/dsl.go
pkg/testinfra/dsl/kcpIpRange.go
pkg/testinfra/dsl/nfsInstance.go

**gcp nfsInstance automated reconciler test**
- automated test for gcp nfsInstance happy path
https://jira.tools.sap/browse/PHX-47

Adding automated test for gcp nfsInstance creation happy path

---

internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/skr/gcpnfsvolume/updateStatus.go
pkg/testinfra/dsl/gcpNfsVolume.go

Completed the automated tests for the SKR GcpNfsVolume happy path.

SKR GcpNfsVolume automated tests

---

internal/controller/cloud-control/nfsinstance_gcp_test.go
pkg/kcp/provider/gcp/mock/nfsStore.go
pkg/testinfra/dsl/nfsInstance.go

**Adding automated test for gcp nfsInstance patch and deletion happy path**
- adding automated test for gcp nfsInstance patch and deletion
See https://jira.tools.sap/browse/PHX-47

Adding automated test for gcp nfsInstance patch and deletion happy path

---

internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/skr/gcpnfsvolume/createPersistenceVolume.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/testinfra/dsl/conditions.go
pkg/testinfra/dsl/gcpNfsVolume.go
pkg/testinfra/dsl/kcpIpRange.go
pkg/testinfra/dsl/objActions.go
pkg/testinfra/dsl/skrIpRange.go

GcpNfsVolume automated testing flow for update.

GcpNfsVolume - Automated flows for update

---

cmd/cli/cmdKymaCreate.go
cmd/cli/cmdKymaList.go
cmd/cli/cmdKymaModuleStateRemove.go
cmd/cli/cmdKymaModuleStateShow.go
cmd/cli/cmdKymaModuleStateUpdate.go
internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/scope_aws_test.go
pkg/kcp/scope/findKymaModuleState.go
pkg/kcp/scope/state.go
pkg/testinfra/dsl.go
pkg/testinfra/dsl/conditions.go
pkg/testinfra/dsl/kyma.go
pkg/testinfra/dsl/utilUpdate.go
pkg/testinfra/gherkin.go
pkg/util/kyma.go
pkg/util/kyma_test.go

- Trigger SKR loop start when module is listed in the KCP Kyma CR spec, and not in status with Ready state as so far
- Refactored the Gherkin report to justify durations and checks on the right margin
- Refactored KCP IpRange AWS and KCP Scope AWS tests into single `It()` to obtain whole log in case of an error

scope reconciler fix

---

pkg/skr/gcpnfsvolume/addFinalizer_test.go
pkg/skr/gcpnfsvolume/createPersistenceVolume.go
pkg/skr/gcpnfsvolume/createPersistenceVolume_test.go
pkg/skr/gcpnfsvolume/loadKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/state_test.go

GcpNfsVolume unit tests for
- Create PV
- Load KCP NfsInstance
https://jira.tools.sap/browse/PHX-52

GcpNfsVolume - UnitTests for CreatePV loadNfsInstance

---

pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/modifyPersistenceVolume_test.go
pkg/skr/gcpnfsvolume/state_test.go

- Unit tests for modify KcpNfsInstance
- Unit tests for modify PV
https://jira.tools.sap/projects/PHX/issues/PHX-52

GcpNfsVolume - Unit tests for modify KcpInstance and PV

---

pkg/skr/gcpnfsvolume/validateSpec_test.go

- ValidateSpec Unit tests
https://jira.tools.sap/browse/PHX-52

GcpNfsVolume Reconciler Unit tests

---

config/rbac/role.yaml
internal/controller/cloud-control/scope_controller.go

fix kymas finalizers rbac

---

config/rbac/role.yaml
internal/controller/cloud-control/scope_controller.go

- Updated rbac to include update for Kyma objects
NA

Updated rbac to include update for Kyma objects

---

Dockerfile

fix docker files chown

---

Dockerfile

change provider files location and permissions

---

Dockerfile

change provider files permissions

---

cmd/main.go
go.mod
pkg/util/gcpLogLevelEncoder.go

- added support for GCP structured logging

gcp structured logging

---

internal/controller/cloud-resources/awsnfsvolume_test.go
pkg/composed/markedForDeletionPredicate.go
pkg/skr/awsnfsvolume/deleteNfsVol.go
pkg/skr/awsnfsvolume/loadKcpNfsInstance.go
pkg/skr/awsnfsvolume/reconciler.go
pkg/skr/awsnfsvolume/removeFinalizer.go
pkg/skr/awsnfsvolume/requeueWaitKcpStatus.go
pkg/skr/awsnfsvolume/stopIfNotBeingDeleted.go
pkg/skr/awsnfsvolume/updateId.go
pkg/skr/awsnfsvolume/updateStatus.go
pkg/skr/awsnfsvolume/waitIpRangeReady.go
pkg/skr/awsnfsvolume/waitKcpNfsInstanceDeleted.go
pkg/skr/awsnfsvolume/waitPvDeleted.go
pkg/testinfra/dsl/commonAssertions.go
pkg/testinfra/dsl/objActions.go

- fixed AwsNfsVolume deprovisioning

fixed AwsNfsVolume deprovisioning

---

pkg/kcp/provider/gcp/client/provider.go
pkg/kcp/provider/gcp/iprange/client/computeClient.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
pkg/kcp/provider/gcp/iprange/new.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/kcp/provider/gcp/nfsinstance/new.go
pkg/skr/iprange/updateStatus.go

- Update GCP IpRange and NfsInstance Status condition with error message when connection to GCP fails.
https://jira.tools.sap/browse/PHX-63

Updting Status Condition when Connecting to GCP fails

---

cmd/cli/cmdKymaCreate.go

cli kyma create

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml

- running config/sync.sh to update the provider yaml files.
Related to recent changes for 
https://jira.tools.sap/browse/PHX-59
https://jira.tools.sap/browse/PHX-60
https://jira.tools.sap/browse/PHX-61

syncing providers

---

internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/nfsinstance_aws_test.go
internal/controller/cloud-control/suite_test.go
internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
internal/controller/cloud-resources/iprange_test.go
pkg/kcp/provider/aws/iprange/createSubnets.go
pkg/kcp/provider/aws/iprange/findCloudResourceSubnets.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/iprange/util.go
pkg/kcp/provider/aws/mock/nfsStore.go
pkg/kcp/provider/aws/mock/vpcStore.go
pkg/kcp/provider/aws/nfsinstance/client/client.go
pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go
pkg/kcp/provider/aws/nfsinstance/loadEfs.go
pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
pkg/kcp/provider/aws/nfsinstance/new.go
pkg/kcp/provider/aws/nfsinstance/removeFinalizer.go
pkg/kcp/provider/aws/nfsinstance/removeReadyCondition.go
pkg/kcp/provider/aws/nfsinstance/updateStatus.go
pkg/kcp/provider/aws/nfsinstance/validateIpRangeSubnets.go
pkg/kcp/provider/aws/nfsinstance/waitEfsDeleted.go
pkg/kcp/provider/aws/nfsinstance/waitMountTargetsDeleted.go
pkg/kcp/provider/aws/util/ec2tags.go
pkg/testinfra/dsl/awsIpRange.go
pkg/testinfra/dsl/awsNfsVolume.go
pkg/testinfra/dsl/conditions.go
pkg/testinfra/dsl/nfsInstance.go

- KCP AWS NfsInstance deprovisioning

feat(AWS NfsInstance): deprovisioning

---

cmd/cli/README.md
tools/dev/README.md

- Update README.md for Cloud Manager CLI
- Update README.md for dev setup

Update cli readme

---

.github/workflows/pr-checks.yml

-  Adding checks to verify if config/dist/skr/crd/bases/providers is up to date.

Checks if config/dist/skr/crd/bases/providers are up to date.

---

pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
pkg/kcp/provider/aws/nfsinstance/loadEfs.go
pkg/kcp/provider/aws/nfsinstance/waitEfsDeleted.go
tools/demo/awsnfsvolume/iprange.yaml

chore: aws nfs deprovisioning fix

---

pkg/kcp/provider/aws/nfsinstance/deleteEfs.go

aws nfs deprovisioning fix

---

internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/nfsinstance_aws_test.go
internal/controller/cloud-control/scope_aws_test.go
internal/controller/cloud-resources/iprange_test.go
pkg/kcp/provider/aws/iprange/client/client.go
pkg/kcp/provider/aws/iprange/deleteSubnets.go
pkg/kcp/provider/aws/iprange/disassociateVpcAddressSpace.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/iprange/new.go
pkg/kcp/provider/aws/iprange/removeFinalizer.go
pkg/kcp/provider/aws/iprange/removeReadyCondition.go
pkg/kcp/provider/aws/iprange/waitCidrBlockDisassociated.go
pkg/kcp/provider/aws/iprange/waitSubnetsDeleted.go
pkg/kcp/provider/aws/mock/vpcStore.go
pkg/kcp/scope/findKymaModuleState.go
pkg/skr/iprange/deleteKcpIpRange.go
pkg/testinfra/gherkin.go
pkg/util/delayActIgnore.go

- added AWS IpRange deprovisioning

feat: AWS IpRange deprovisioning

---

api/cloud-resources/v1beta1/awsnfsvolume_types.go
api/cloud-resources/v1beta1/cloudresources_types.go
api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/iprange_types.go
config/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
config/dist/skr/crd/bases/cloud-resources.kyma-project.io_cloudresources.yaml
internal/controller/cloud-control/scope_aws_test.go
pkg/composed/list.go
pkg/kcp/scope/findKymaModuleState.go
pkg/kcp/scope/reconciler.go
pkg/kcp/scope/skrDeactivate.go
pkg/kcp/scope/state.go
pkg/kcp/scope/stopIfReady.go
pkg/skr/cloudresources/checkIfResourcesExist.go
pkg/skr/cloudresources/handleServed.go
pkg/skr/cloudresources/reconciler.go
pkg/skr/cloudresources/removeFinalizer.go
pkg/skr/cloudresources/state.go
pkg/skr/cloudresources/stateReady.go
pkg/skr/runtime/looper/runner.go
pkg/skr/runtime/reconcile/reconcilerFactory.go
pkg/testinfra/run.go

- cloud-manager module deprovisioning

feat: module deprovisioning

---

pkg/kcp/scope/reconciler.go
pkg/kcp/scope/stopIfReadyAndActive.go
pkg/skr/runtime/looper/skrLooper.go

chore: module deprovisioning fixes

---

pkg/kcp/scope/findKymaModuleState.go
pkg/skr/cloudresources/handleServed.go

chore: module deprovisioning fix

---

pkg/common/actions/focal/loadScopeFromRef.go
pkg/composed/updateStatus.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/iprange/new.go
pkg/kcp/provider/aws/iprange/state.go
pkg/kcp/provider/gcp/iprange/loadAddress_test.go
pkg/kcp/provider/gcp/iprange/loadPsaConnection_test.go
pkg/kcp/provider/gcp/iprange/syncAddress_test.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
pkg/kcp/provider/gcp/iprange/updateState_test.go
pkg/kcp/provider/gcp/iprange/validateCidr_test.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
pkg/kcp/provider/gcp/nfsinstance/validatePostCreate_test.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume_test.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/updateStatus_test.go
pkg/skr/gcpnfsvolume/validateSpec_test.go

- improve debugging log messages

chore: improve debugging log messages

---

pkg/kcp/scope/removeKymaFinalizer.go
pkg/util/gcpLogLevelEncoder.go

- fixing scope remove kyma finalizer

chore: fixing scope remove kyma finalizer

---

sec-scanners-config.yaml

- Update sec-scanners-config.yaml v20240327-3713616a

Update sec-scanners-config.yaml v20240327-3713616a

---

pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
pkg/skr/iprange/updateStatus.go

- Fix for empty error messages during GCP reconcile
- Having only one Condition (either Error or Ready) in SKR IpRange status.
NA

fix: Error messages during Gcp reconcile

---

config/manager/kustomization.yaml
pkg/kcp/provider/gcp/client/provider.go
pkg/kcp/provider/gcp/client/provider_test.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go

- Renewing gcp http client periodically
https://jira.tools.sap/browse/PHX-74

feat: renew gcp http client periodically

---

api/cloud-control/v1beta1/vpcpeering_types.go
cmd/main.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
internal/controller/cloud-control/suite_test.go
internal/controller/cloud-control/vpcpeering_aws_test.go
internal/controller/cloud-control/vpcpeering_controller.go
pkg/kcp/provider/aws/mock/server.go
pkg/kcp/provider/aws/mock/type.go
pkg/kcp/provider/aws/vpcpeering/addFinalizer.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/loadVpc.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/state.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
pkg/kcp/vpcpeering/reconciler.go
pkg/kcp/vpcpeering/state.go
pkg/kcp/vpcpeering/types/state.go
pkg/testinfra/dsl/kcpVpcPeering.go

- KCP AWS VpcPeering reconciliation
-   addFinalizer
-   loadVpc
-   updateStatusSuccess

feat: KCP AWS VpcPeering create

---

internal/controller/cloud-control/iprange_gcp_test.go
internal/controller/cloud-control/nfsinstance_gcp_test.go
internal/controller/cloud-control/scope_gcp_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/testinfra/dsl.go

- Increased the timeouts for GCP test cases to 20 seconds.
- Added a delay of 1s before the IpRange creation.
- Changed test case names to include Feature and Scenario tags.
https://jira.tools.sap/browse/PHX-78

fix: Gcp IpRange Test

---

internal/controller/cloud-resources/iprange_test.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/validateCidr.go
pkg/testinfra/run.go

- prevent IpRanges with length smaller then /16

feat: prevent IpRanges with length smaller then /16

---

api/cloud-control/v1beta1/vpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/mock/server.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/state.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go

- Add provider to state so that remote vpc can be loaded
- load remote vpc into state
- create vpc peering connection mocks
- integration tests updated

feat: KCP AWS VpcPeering load remote vpc

---

internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/nfsinstance_aws_test.go
internal/controller/cloud-control/vpcpeering_aws_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/common/consts.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/nfsinstance/createEfs.go
pkg/kcp/scope/skrActivate.go
pkg/kcp/scope/skrDeactivate.go
pkg/metrics/skrRuntime.go
pkg/skr/runtime/looper/skrLooper.go
pkg/testinfra/crd.go
pkg/testinfra/dsl/ginkgo.go
pkg/testinfra/gherkin.go
pkg/testinfra/run.go

- choose correct vpc for IpRange

fix: choose correct vpc for IpRange

---

config/samples/cloud-resources_v1beta1_awsnfsvolume.yaml
config/samples/cloud-resources_v1beta1_cloudresources.yaml
config/samples/cloud-resources_v1beta1_iprange.yaml
pkg/kcp/provider/aws/mock/vpcStore.go
pkg/kcp/provider/aws/nfsinstance/client/client.go
pkg/kcp/provider/aws/nfsinstance/new.go
pkg/kcp/provider/aws/nfsinstance/removeMountTargetsFromOtherVpcs.go

- ensure same vpc mount targets in single efs

chore(AwsNfsVolume): ensure same vpc mount targets in single efs

---

.github/workflows/pr-checks.yml
api/cloud-resources/v1beta1/awsnfsvolume_types.go
api/cloud-resources/v1beta1/condition.go
api/cloud-resources/v1beta1/iprange_types.go
api/cloud-resources/v1beta1/state.go
config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
internal/controller/cloud-resources/iprange_controller.go
internal/controller/cloud-resources/iprange_test.go
pkg/skr/awsnfsvolume/ignorant.go
pkg/skr/iprange/preventCidrChange.go
pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/updateStatus.go
pkg/skr/iprange/validateCidr.go
pkg/skr/runtime/looper/runner.go
pkg/skr/runtime/registry/indexer.go
pkg/skr/runtime/registry/registry.go
pkg/testinfra/crd.go

- prevent SKR IpRange deletion when used by AwsNfsVolume
- added SKR IpRange.status.state field
- added indexer support to SkrRuntime registry

feat: prevent SKR IpRange deletion when used by AwsNfsVolume

---

sec-scanners-config.yaml

- updated security scan config to image v0.1.4

chore: sec scan config v0.1.4

---

sec-scanners-config.yaml

chore: sec scan config 0.1.4

---

pkg/kcp/provider/azure/nfsinstance/new.go

chore: Checkmarx  Error Handling azure/nfsinstance

---

pkg/composed/predicate.go
pkg/kcp/scope/findKymaModuleState.go
pkg/kcp/scope/loadKyma.go
pkg/kcp/scope/loadScopeObj.go
pkg/skr/awsnfsvolume/updateStatus.go
pkg/skr/runtime/looper/installer.go
pkg/skr/runtime/looper/runner.go
pkg/skr/runtime/looper/skrLooper.go

chore: reduce scope logging

---

sec-scanners-config.yaml

chore: sec scan 0.1.5

---

Makefile
config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
config/patchAfterMakeManifests.sh
pkg/skr/runtime/looper/installer.go

- fixed skr installer to update CRD with new version

fix: skr installer update new CRD version

---

sec-scanners-config.yaml

chore: security scanner 0.1.6

---

cmd/cli/helper/k8s.go

- cli was not picking the value of CM_CONTEXT_GARDEN

fix: cli is not picking the env variable value

---

api/cloud-resources/v1beta1/iprange_types.go
internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
internal/controller/cloud-resources/iprange_test.go
pkg/skr/awsnfsvolume/updateStatus.go
pkg/skr/iprange/preventCidrOverlap.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/validateCidr.go

- SKR IpRange prevent CIDR overlap

fix: SKR IpRange prevent CIDR overlap

---

pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/state.go

- Propagate roleName from ENV to state

fix: AWS VpcPeering propagate roleName

---

cmd/main.go
internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go

fix: empty gcpnfsbackup factory

---

cmd/main.go
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/sync.sh
internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/skr/gcpnfsvolumebackup/addFinalizer.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadNfsInstance.go
pkg/skr/gcpnfsvolumebackup/loadScope.go
pkg/skr/gcpnfsvolumebackup/reconciler.go
pkg/skr/gcpnfsvolumebackup/removeFinalizer.go
pkg/skr/gcpnfsvolumebackup/state.go
pkg/skr/gcpnfsvolumebackup/updateStatus.go

- GcpNfsVolumeBackup Reconciler
- Add/Remove Finalizers
- CreateBackup
- DeleteBackup
https://jira.tools.sap/browse/PHX-85

GcpNfsVolumeBackup POC

---

cmd/main.go

- Commented out starting of GcpNfsVolumeBackup controller.
https://jira.tools.sap/browse/PHX-85

fix: Not starting GcpNfsVolumeBackup controller

---

pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/state.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go

- Create vpc peering connection

Aws vpc peering create connection

---

CODEOWNERS
go.mod
go.sum
pkg/common/abstractions/environment.go
pkg/config/README.md
pkg/config/binding.go
pkg/config/config.go
pkg/config/config_bind_test.go
pkg/config/config_raw_test.go
pkg/config/config_watch_test.go
pkg/config/fieldPath.go
pkg/config/fieldPath_test.go
pkg/config/sourceEnv.go
pkg/config/sourceFile.go
pkg/config/testdata/file-v1.yaml
pkg/config/testdata/file-v2.yaml
pkg/config/testdata/first.json
pkg/config/testdata/first.yaml
pkg/config/testdata/resourceQuotaDefault.json
pkg/config/testdata/resourceQuotaDefault.yaml
pkg/config/testdata/resourceQuotaOverride.json
pkg/config/testdata/resourceQuotaOverride.yaml
pkg/config/testdata/scalar
pkg/config/types.go
pkg/config/util_test.go
pkg/config/watchedState.go

- merged config from env and file sources with automatic reload when file changed

chore: config 

---

api/cloud-control/v1beta1/vpcpeering_types.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/new.go

- AWS VpcPeering accept vpc peering connection

feat: AWS VpcPeering accept vpc peering connection

---

sec-scanners-config.yaml

chore: sec scan rc 0.1.7

---

config/ui-extensions/awsnfsvolumes/general
config/ui-extensions/awsnfsvolumes/kustomization.yaml
config/ui-extensions/cloudresources/general
config/ui-extensions/cloudresources/kustomization.yaml
config/ui-extensions/gcpnfsvolumes/details
config/ui-extensions/gcpnfsvolumes/form
config/ui-extensions/gcpnfsvolumes/general
config/ui-extensions/gcpnfsvolumes/kustomization.yaml
config/ui-extensions/gcpnfsvolumes/list
config/ui-extensions/gcpnfsvolumes/translations
config/ui-extensions/ipranges/form
config/ui-extensions/ipranges/general
config/ui-extensions/ipranges/kustomization.yaml
config/ui-extensions/ipranges/list
config/ui-extensions/kustomization.yaml

- First pass of GCPNfsVolume UI
- ...
- ...

feat: GcpNfsVolume UI First Pass

---

pkg/skr/iprange/preventCidrOverlap.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/removeOverlapCondition.go

fix: iprange cidr overlap can be removed

---

pkg/skr/iprange/checkQuota.go

fix: quota allow older resources, put error on newer

---

api/cloud-resources/v1beta1/condition.go
internal/controller/cloud-resources/cr/doc.go
internal/controller/cloud-resources/quotaIpRange/doc.go
internal/controller/cloud-resources/quotaIpRange/quotaIpRange_test.go
internal/controller/cloud-resources/quotaIpRange/suite_test.go
pkg/common/ignorant/store.go
pkg/skr/iprange/checkQuota.go
pkg/skr/iprange/preventCidrChange.go
pkg/skr/iprange/validateCidr.go
pkg/testinfra/infra.go

fix: SKR IpRange quota

---

sec-scanners-config.yaml

chore: sec-scan-0.1.8

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml

feat: added gcpnfsvolumes ui ConfigMap to provider location

---

cmd/main.go
config/manager/kustomization.yaml
internal/controller/cloud-resources/gcpnfsvolumebackup_controller.go
internal/controller/cloud-resources/gcpnfsvolumerestore_controller.go
pkg/skr/runtime/looper/installer.go
pkg/util/featureFlag.go

- Feature flag  to disable controller and CRD def deployment
https://jira.tools.sap/browse/PHX-112

feat: Feature flag  to disable controller and CRD def deployment

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml

…svolumes_ui.yaml
- ...
- ...
- ...

(bug) gcpnfsvolume-ui namespace

---

pkg/kcp/provider/gcp/client/provider.go
pkg/kcp/provider/gcp/client/serviceUsageClient.go
pkg/kcp/provider/gcp/iprange/client/computeClient.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/kcp/provider/gcp/nfsrestore/client/fileRestoreClient.go
pkg/metrics/cloudProvider.go

- Updated periodic http client renewal to include Authentication Check
- Report metrics to Prometheus
- Report metrics to Prometheus on all GCP calls.
https://jira.tools.sap/browse/PHX-110

feat: GCP Principal Credential Authentication tester

---

go.mod
pkg/kcp/provider/gcp/client/provider.go

Fix for the GCP Authentication Check. Invoking google APIs requires additional roles on the GCP project. Changed the implementation to generate and use JWT token and perform authentication only.
https://jira.tools.sap/browse/PHX-110

fix: GCP Authentication Check

---

internal/controller/cloud-control/suite_test.go
internal/controller/cloud-resources/suite_test.go
pkg/kcp/provider/aws/config/config.go
pkg/kcp/provider/aws/iprange/createSubnets.go
pkg/kcp/provider/aws/iprange/deleteSubnets.go
pkg/kcp/provider/aws/iprange/disassociateVpcAddressSpace.go
pkg/kcp/provider/aws/iprange/extendVpcAddressSpace.go
pkg/kcp/provider/aws/iprange/loadSubnets.go
pkg/kcp/provider/aws/iprange/loadVpc.go
pkg/kcp/provider/aws/iprange/new.go
pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/nfsinstance/authorizeSecurityGroupIngress.go
pkg/kcp/provider/aws/nfsinstance/createEfs.go
pkg/kcp/provider/aws/nfsinstance/createMountTargets.go
pkg/kcp/provider/aws/nfsinstance/createSecurityGroup.go
pkg/kcp/provider/aws/nfsinstance/deleteEfs.go
pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go
pkg/kcp/provider/aws/nfsinstance/findSecurityGroup.go
pkg/kcp/provider/aws/nfsinstance/loadEfs.go
pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go
pkg/kcp/provider/aws/nfsinstance/loadSecurityGroup.go
pkg/kcp/provider/aws/nfsinstance/new.go
pkg/kcp/provider/aws/nfsinstance/removeMountTargetsFromOtherVpcs.go
pkg/kcp/provider/gcp/client/provider.go
pkg/metrics/cloudProvider.go
pkg/metrics/cloudProviderAws.go
pkg/util/timing.go

fix(aws): requeue delayed in case of a retryable error

---

pkg/composed/action.go
pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/nfsinstance/deleteMountTargets.go
pkg/util/timing.go

fix(AwsNfsVolume): requeue when mount targets are deleted

---

pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go

fix(AwsNfsVolume): ignore filesystem not found error when loading mount targets

---

pkg/kcp/provider/aws/nfsinstance/loadMountTargets.go

fix(AwsNfsVolume): ignore mount target not found error

---

internal/controller/cloud-control/nfsinstance_controller.go
internal/controller/cloud-resources/cr/suite_test.go
internal/controller/cloud-resources/quotaIpRange/suite_test.go
pkg/kcp/provider/aws/nfsinstance/createMountTargets.go

fix(AwsNfsVolume): wait until mount targets are available

---

pkg/kcp/provider/aws/nfsinstance/deleteSecurityGroup.go

chore(AwsNfsVolume): wait for security group to be deleted

---

sec-scanners-config.yaml

chore: sec scan 0.1.9

---

internal/controller/cloud-resources/gcpnfsvolumerestore_test.go
internal/controller/cloud-resources/suite_test.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/skr/gcpnfsvolume/ignorant.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolumebackup/ignorant.go
pkg/skr/gcpnfsvolumebackup/reconciler.go
pkg/testinfra/dsl/gcpNfsVolumeBackup.go
pkg/testinfra/dsl/gcpNfsVolumeRestore.go
pkg/testinfra/dsl/loadAndCheck.go

- integration tests for GcpNfsVolumeRestore reconciler
https://jira.tools.sap/browse/PHX-120

test: integration tests for GcpNfsVolumeRestore reconciler

---

internal/controller/cloud-control/suite_test.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/mock/ctx.go
pkg/kcp/provider/azure/mock/server.go
pkg/kcp/provider/azure/mock/type.go
pkg/kcp/provider/azure/mock/vpcPeeringStore.go
pkg/kcp/provider/azure/vpcpeering/client/client.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/updateSuccessStatus.go
pkg/testinfra/dsl/conditions.go
pkg/testinfra/dsl/kcpVpcPeering.go
pkg/testinfra/dsl/scope.go
pkg/testinfra/env.go
pkg/testinfra/run.go
pkg/testinfra/types.go

- Added Azure mocks
- Create KCP VpcPeering from kyma to remote

feat (AzureVpcPeering): KCP Create VpcPeering from kyma to remote

---

api/cloud-control/v1beta1/vpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/samples/cloud-control_v1beta1_vpcpeering.yaml
internal/controller/cloud-control/vpcpeering_aws_test.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/kcp/provider/azure/mock/vpcPeeringStore.go
pkg/kcp/provider/azure/util/resources.go
pkg/kcp/provider/azure/util/resources_test.go
pkg/kcp/provider/azure/vpcpeering/client/client.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringRemote.go
pkg/kcp/provider/azure/vpcpeering/new.go

- Creates peering from remote subscription to Kyma subscription
- Updating tests

feat(AzureVpcPeering): KCP Create VpcPeering from remote to Kyma

---

internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
internal/controller/cloud-resources/suite_test.go
pkg/kcp/provider/gcp/mock/nfsBackupStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/testinfra/dsl/gcpNfsVolumeBackup.go

Integration tests for
- Creation of GcpNfsVolumeBackup
- Deletion of GcpNfsVolumeBackup
https://jira.tools.sap/browse/PHX-122

test: GcpNfsVolumeBackup integration tests

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
internal/controller/cloud-control/nfsinstance_gcp_test.go
pkg/kcp/provider/gcp/client/gcpConstants.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
pkg/skr/gcpnfsvolume/deletePVForNameChange.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume_test.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/updateStatus.go
pkg/skr/gcpnfsvolume/updateStatus_test.go
pkg/skr/gcpnfsvolume/validatePV.go
pkg/skr/gcpnfsvolume/validateSpec.go
pkg/skr/gcpnfsvolume/validateSpec_test.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadScope.go
pkg/skr/gcpnfsvolumebackup/updateStatus.go
pkg/skr/gcpnfsvolumebackup/updateStatus_test.go

- State attribute added to GcpNfsVolume.Status
- State attribute added to GcpNfsVoluumeBackup.Status
https://jira.tools.sap/browse/PHX-125
https://jira.tools.sap/browse/PHX-126

feat: GcpNfsVolume and GcpNfsVolumeBackup Status.State

---

api/cloud-resources/v1beta1/iprange_types.go
api/cloud-resources/v1beta1/state.go
pkg/composed/updateStatus.go
pkg/skr/iprange/checkQuota.go
pkg/skr/iprange/createKcpIpRange.go
pkg/skr/iprange/deleteKcpIpRange.go
pkg/skr/iprange/preventCidrChange.go
pkg/skr/iprange/preventCidrOverlap.go
pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/setProcessingStateForDeletion.go
pkg/skr/iprange/state.go
pkg/skr/iprange/updateId.go
pkg/skr/iprange/updateStatus.go
pkg/skr/iprange/validateCidr.go
pkg/skr/runtime/manager/factory.go

- Unify Cloud Manager SKR CR Statuses - iprange
https://jira.tools.sap/browse/PHX-124

chore(SKR IpRange): SKR CR Statuses Unification

---

pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/updateStatus.go

- KCP stop when peered and ready

feat(AzureVpcPeering): KCP stop when peered and ready

---

.github/workflows/pr-checks.yml
Makefile
config/sync.sh
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/kustomization.yaml

(feat) updated make and sync file to build and copy ui YAMLs

---

api/cloud-resources/v1beta1/awsnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
internal/controller/cloud-resources/awsnfsvolume_test.go
pkg/skr/awsnfsvolume/createKcpNfsInstance.go
pkg/skr/awsnfsvolume/deletePv.go
pkg/skr/awsnfsvolume/loadSkrIpRange.go
pkg/skr/awsnfsvolume/updateId.go
pkg/skr/awsnfsvolume/updateStatus.go
pkg/testinfra/dsl/awsNfsVolume.go

- AwsNfsVolume State and Conditions unification
https://jira.tools.sap/browse/PHX-128

chore(AwsNfsVolume): State and Status unification

---

.github/workflows/pr-checks.yml
internal/controller/cloud-control/vpcpeering_aws_test.go

chore: Check if test GUIDs are unique

---

api/cloud-resources/v1beta1/iprange_types.go
config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
internal/controller/cloud-resources/gcpnfsvolume_test.go
internal/controller/cloud-resources/iprange_test.go
internal/controller/cloud-resources/suite_test.go
pkg/kcp/iprange/allocate/addressSpace.go
pkg/kcp/iprange/allocate/rangeList.go
pkg/skr/iprange/deleteKcpIpRange.go
pkg/skr/iprange/preventCidrChange.go
pkg/skr/iprange/preventCidrOverlap.go
pkg/skr/iprange/updateStatus.go
pkg/skr/iprange/validateCidr.go
pkg/testinfra/dsl/objActions.go

- changed SKR IpRange spec.cidr to be optional
- modified SKR IpRange reconciler to allow empty cidr
- modified SKR IpRange cidr overlap algo to allow only one IpRange with empty cidr
- added integration test for IpRange with empty cidr

feat: optional SKR IpRange cidr

---

config/featureToggles/featureToggles.yaml
pkg/common/actions/focal/loadKyma.go

- fixed loading of Kyma CR in the focal package

fix: load of Kyma CR for feature context loading

---

pkg/skr/iprange/preventCidrOverlap.go

fix(SKR IpRange): optional cidr and overlap check

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/translations
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/translations
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/ipranges/list
config/ui-extensions/ipranges/translations

(feat) added translations for backups, restores, ipranges

---

cmd/main.go
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/sync.sh
pkg/kcp/provider/azure/config/config.go

- Starting SKR AzureVpcPeering controller
- Copying AzureVpcPeering CRD to providers directory
- Renaming environment variables

feat(AzureVpcPeering): start SKR controller

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/kustomization.yaml
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/kustomization.yaml
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/kustomization.yaml
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/ipranges/kustomization.yaml

(feat) cloud-manager: ui-cm label

---

pkg/kcp/provider/aws/iprange/v2/subnetsCreate.go

- added additional logs in KCP AWS IpRange to log status subnets before and after subnet creation

chore(KCP AWS IpRange): additional logs

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml

- Removed Server from the printable column list
https://jira.tools.sap/browse/PHX-146

chore(GcpNfsVolume): Removed Server from the printable column list

---

config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/patchAfterMakeManifests.sh

- added version label on AwsNfsVolume CRD

chore(AwsNfsVolume): crd version bump

---

pkg/common/objSupportsProvider.go
pkg/kcp/provider/aws/iprange/v2/statusSuccess.go
pkg/skr/runtime/looper/installer.go
pkg/skr/runtime/looper/runner.go

fix(SRK runtime): check provider

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/details
config/ui-extensions/gcpnfsvolumebackups/translations
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/details
config/ui-extensions/gcpnfsvolumerestores/translations
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/details
config/ui-extensions/gcpnfsvolumes/translations
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/ipranges/details
config/ui-extensions/ipranges/translations

(feat) GCP NfsVolume, Backup, Restore, IpRange detail polish

---

Makefile
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/sync.sh
config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/ui-extensions/awsnfsvolumes/details
config/ui-extensions/awsnfsvolumes/general
config/ui-extensions/awsnfsvolumes/kustomization.yaml
config/ui-extensions/awsnfsvolumes/list
config/ui-extensions/awsnfsvolumes/translations
config/ui-extensions/kustomization.yaml

(feat) AWSnfsvolumes ui

---

Makefile
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/sync.sh
config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/gcpvpcpeerings/details
config/ui-extensions/gcpvpcpeerings/general
config/ui-extensions/gcpvpcpeerings/kustomization.yaml
config/ui-extensions/gcpvpcpeerings/list
config/ui-extensions/gcpvpcpeerings/translations

(feat) gcp vpcpeering UI

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/sync.sh

(feat) added iprange ui to aws provider

---

pkg/kcp/provider/aws/iprange/v1/checkCidrOverlap.go

- Handle potential error on IpRange cidr parse

fix(IpRange): handle potential error on kcp iprangrange cidr parse

---

pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go

add more logs to modify persistence volume action

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/ui-extensions/awsnfsvolumes/details
config/ui-extensions/awsnfsvolumes/form
config/ui-extensions/awsnfsvolumes/translations
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/form
config/ui-extensions/gcpnfsvolumebackups/translations
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/form
config/ui-extensions/gcpnfsvolumerestores/translations
config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/gcpvpcpeerings/form

(feat) UI Form Polish

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml

(feat) updated gcpnfsvolume_types.go so Tier is now an enum

---

pkg/skr/gcpnfsvolume/modifyPersistenceVolume.go
pkg/skr/gcpnfsvolume/util.go

return empty map for annotations if PV(C) does not exist

---

internal/controller/cloud-resources/gcpnfsvolume_test.go

chore(GcpNfsVolume): update scenario test to confirm finalizers are added to PV and PVC

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/details
config/ui-extensions/gcpnfsvolumes/list
config/ui-extensions/gcpnfsvolumes/translations
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/ipranges/list
config/ui-extensions/ipranges/translations

(chore) Added missing Status on List and Detail

---

pkg/skr/gcpnfsvolume/validatePV.go
pkg/skr/gcpnfsvolume/validatePV_test.go

- fixes existing validatePV implementation
- adds unit tests for validatePV

fix(GcpNfsVolume): fix validatePV and add tests for it

---

pkg/skr/gcpnfsvolume/validatePV.go
pkg/skr/gcpnfsvolume/validatePVC.go

- changes error message for validatePV and validatePVC

chore(GcpNfsVolume): change validatePV and validatePVC error msg format

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
pkg/skr/gcpnfsvolume/deletePVForNameChange.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume.go
pkg/skr/gcpnfsvolume/deletePersistentVolumeClaim.go
pkg/skr/gcpnfsvolume/loadKcpIpRange.go
pkg/skr/gcpnfsvolume/loadKcpIpRange_test.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/state.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/skr/gcpnfsvolume/updateStatus.go
pkg/skr/gcpnfsvolume/validateSpec.go
pkg/testinfra/dsl/gcpNfsVolume.go

- Making IpRange Optional for gcpNfsVolume
https://jira.tools.sap/browse/PHX-166

feat(GcpNfsVolume): optional iprange

---

go.mod
go.sum
internal/controller/cloud-control/vpcpeering_controller.go
pkg/kcp/provider/gcp/cloudclient/provider.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/vpcpeering/client/cloudComputeClient.go
pkg/kcp/provider/gcp/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/gcp/vpcpeering/state.go
pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
pkg/skr/gcpvpcpeering/updateStatus.go

- Remote network(vpc) tag check
- Fixes continued sync after initial sync to skr

feat(GCPVpcPeering) Adding remote network tag check

---

pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go

- hides azure API errors from the user

feat (AzureVpcPeering): handling API errors

---

pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpc.go
pkg/skr/azurevpcpeering/updateId.go
pkg/skr/azurevpcpeering/updateStatus.go

- handles authorization and resource not found errors

feat (AzureVpcPeering): handling authorization and resource not found

---

PROJECT
api/cloud-resources/v1beta1/iprange_ref.go
api/cloud-resources/v1beta1/iprange_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges.yaml
internal/controller/cloud-resources/iprange_controller.go
internal/controller/cloud-resources/iprange_test.go
pkg/skr/common/defaultiprange/createDefaultSkrIpRange.go
pkg/skr/common/defaultiprange/findDefaultSkrIpRange.go
pkg/skr/common/defaultiprange/new.go
pkg/skr/gcpnfsvolume/loadKcpIpRange.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/skr/gcpnfsvolume/validateSpec_test.go
pkg/skr/gcpnfsvolumebackup/state_test.go
pkg/skr/gcpnfsvolumerestore/state_test.go
pkg/skr/iprange/createKcpIpRange.go
pkg/skr/iprange/preventCidrOverlap.go
pkg/skr/iprange/preventDeleteOnAwsNfsVolumeUsage.go
pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
pkg/testinfra/dsl/awsNfsVolume.go
pkg/testinfra/dsl/gcpNfsVolume.go
pkg/testinfra/dsl/skrIpRange.go
tools/scripts/kcp/listSkrs.mjs

- change SKR IpRange to cluster scope

feat(SKR IpRange): change SKR IpRange to cluster scope

---

pkg/skr/runtime/looper/skrLooper.go

fix: feature landscape logging

---

pkg/skr/runtime/looper/runner.go

chore: SKR runner additional log attributes

---

pkg/kcp/redisinstance/loadIpRange.go
pkg/kcp/redisinstance/reconciler.go

chore: change import alias to match the actual import

---

cmd/main.go
pkg/config/config.go
pkg/config/types.go

chore: config reload

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/awsnfsvolumes/cloud-resources.kyma-project.io_awsnfsvolumes_ui.yaml
config/ui-extensions/awsnfsvolumes/details
config/ui-extensions/awsnfsvolumes/form
config/ui-extensions/awsnfsvolumes/translations
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/details
config/ui-extensions/gcpnfsvolumebackups/translations
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/details
config/ui-extensions/gcpnfsvolumes/form
config/ui-extensions/gcpnfsvolumes/translations
config/ui-extensions/ipranges/cloud-resources.kyma-project.io_ipranges_ui.yaml
config/ui-extensions/ipranges/form
config/ui-extensions/ipranges/list

(chore) bring UI parity for existing cloud manager items

---

README.md

docs: Update Main Readme

---

pkg/config/binding.go
pkg/skr/runtime/config/config.go
pkg/skr/runtime/looper/cyclicQueue.go
pkg/skr/runtime/looper/cyclicQueue_smoke_test.go
pkg/skr/runtime/looper/skrLooper.go

- added skrLooper concurrency config filed
- added CyclicQueue to better control SKR looping
- refactored SkrLooper to use CyclicQueue

chore: SKR Looper configurable concurrency

---

pkg/skr/runtime/looper/skrLooper.go

chore: skrLooper log field workerId

---

pkg/kcp/provider/gcp/client/gcpConstants.go
pkg/kcp/scope/enableApisGcp.go

feat(Scope): enable GCP MemoryStore for Redis

---

pkg/skr/runtime/looper/installer.go

chore: ccee scope installer fix

---

docs/user/resources/04-30-10-gcp-nfs-volume.md

- Updated sample GcpNfsVolume in 04-30-10-gcp-nfs-volume.md
Resolves #358

docs: Update sample GcpNfsVolume in GcpNfsVolume resource doc

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
internal/controller/cloud-control/redisinstance_aws_test.go
internal/controller/cloud-resources/awsredisinstance_test.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/createSubnetGroup.go
pkg/skr/awsredisinstance/createKcpRedisInstance.go
pkg/testinfra/dsl/awsRedisInstance.go
pkg/testinfra/dsl/redisInstance.go

- spec field to define `CacheNodeType` (required)
- spec field to define `EngineVersion` (optional, defaults to `7.0`)
- spec field to define `AutoMinorVersionUpgrade` (optional, defaults to `false`)

feat(AwsRedisInstance): add specs for definition of machine details

---

.github/workflows/pr-golang-lint.yml

chore: upgrade golangci-lint action to v6.0.1

---

pkg/kcp/provider/gcp/iprange/v2/updateStatusId.go

chore(IpRange): add logs for .status.id update

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
api/cloud-resources/v1beta1/gcpredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
config/patchAfterMakeManifests.sh

- enumerates GcpRedisInstance.Tier
- changes jsonPath for GcpRedisInstance and AwsRedisInstance

feat(GcpRedisInstance,RedisInstance) update types

---

api/cloud-resources/v1beta1/labels.go
internal/controller/cloud-resources/awsredisinstance_test.go
internal/controller/cloud-resources/gcpredisinstance_test.go
pkg/kcp/provider/gcp/redisinstance/state.go
pkg/skr/awsredisinstance/loadAuthSecret.go
pkg/skr/awsredisinstance/loadKcpRedisInstance.go
pkg/skr/awsredisinstance/reconciler.go
pkg/skr/awsredisinstance/util.go
pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
pkg/skr/gcpredisinstance/loadAuthSecret.go
pkg/skr/gcpredisinstance/util.go

refactor: change names too match context

---

api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml

- Adds validation from immutable fields

feat (AzureVpcPeering): adds validation for immutable fields

---

api/cloud-resources/v1beta1/awsvpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml

- Adds validation for immutable fields

feat (AwsVpcPeering): adds validation for immutable fields

---

internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/util/ec2tags.go
pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/skr/awsvpcpeering/createKcpVpcPeering.go

- adds support to peer remote vpc network with multiple kyma clusters
- adding tags to aws provisioned resources

feat (AwsVpcPeering): supports peering remote vpc network with multiple kyma clusters

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
pkg/skr/azurevpcpeering/createKpcVpcPeering.go

- adds support to peer remote vpc network with multiple kyma clusters

feat (AzureVpcPeering): supports peering remote vpc network with multiple kyma clusters

---

cmd/cli/README.md
docs/contributor/architecture/README.md
docs/user/README.md

- Change enable and disable to add and delete in the cloud-manager repo
https://github.com/kyma-project/kyma/issues/18735

Change enable and disable to add and delete in the cloud-manager repo

---

Makefile
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/sync.sh
config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/details
config/ui-extensions/awsvpcpeerings/form
config/ui-extensions/awsvpcpeerings/general
config/ui-extensions/awsvpcpeerings/kustomization.yaml
config/ui-extensions/awsvpcpeerings/translations

(feat) AWS VPC Peering UI

---

pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadVpc.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/state.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go

- loads remote vpc peering connection

feat (AwsVpcPeering): loads remote VpcPeering

---

api/cloud-control/v1beta1/vpcpeering_types.go
api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/skr/azurevpcpeering/createKpcVpcPeering.go
pkg/testinfra/dsl/kcpVpcPeering.go

- allows user to specify remotePeeringName

feat (AzureVpcPeering): allows user to specify remotePeeringName

---

pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go

fix(AwsRedisInstance): pass param group name when creating cache

---

Makefile
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/sync.sh
config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/ui-extensions/gcpnfsbackupschedules/details
config/ui-extensions/gcpnfsbackupschedules/form
config/ui-extensions/gcpnfsbackupschedules/general
config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml
config/ui-extensions/gcpnfsbackupschedules/list
config/ui-extensions/gcpnfsbackupschedules/translations

 (feat) GCP NFS Backup Schedules UI

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/ui-extensions/gcpnfsbackupschedules/form

(bugFix) removed all fields from nfsVolumeRef except name and namespace

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/details
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/azurevpcpeerings/translations

AWSRedisInstance & AzureVPCPeering UI Update

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form

(bugFix) updated GCP Redis Instance UI

---

api/cloud-control/v1beta1/redisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
pkg/kcp/provider/gcp/redisinstance/updateStatus.go
pkg/skr/gcpredisinstance/util.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/427

feat(RedisInstance,GcpRedisInstance): put CaCert.pem in auth secret

---

pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/util/labels.go
pkg/util/labels_test.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/432

feat(GcpRedisInstance): add labels to gcp redis instance

---

api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml

- Defaults AllowVnetAccess to true

feat (AzureVpcPeering): defaults allowVnetAccess to true

---

api/cloud-control/v1beta1/nfsinstance_gcp_types.go
api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/zz_generated.deepcopy.go
config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
internal/controller/cloud-control/nfsinstance_gcp_test.go
pkg/kcp/provider/gcp/nfsinstance/state.go
pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup.go
pkg/skr/gcpnfsvolume/loadGcpNfsVolumeBackup_test.go
pkg/skr/gcpnfsvolume/loadScope.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/state.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/testinfra/dsl.go
pkg/testinfra/dsl/nfsInstance.go

- adding support for restore while creating new Filestore
- adding unit / integration tests
Resolves #455

feat(GcpNfsVolume) Support restore when creating a new FileStore

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/details
config/ui-extensions/gcpnfsvolumes/form
config/ui-extensions/gcpnfsvolumes/translations

(feat) added sourceBackup for gcpnfsvolumes UI

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/translations

(feat) added maintenancePolicy for gcpredisinstance

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/patchAfterMakeManifests.sh
config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
internal/controller/cloud-control/redisinstance_aws_test.go
internal/controller/cloud-resources/awsredisinstance_test.go
pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/mock/server.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/deleteElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/state.go
pkg/kcp/provider/aws/redisinstance/updateStatus.go
pkg/kcp/provider/aws/redisinstance/updateStatusId.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
pkg/skr/awsredisinstance/createKcpRedisInstance.go
pkg/testinfra/dsl/awsRedisInstance.go
pkg/testinfra/dsl/redisInstance.go

- adds option to turn on transit encryption
- switches from using `CreateElastiCache` to `CreateReplicationGroup` API
https://github.com/kyma-project/cloud-manager/issues/435

feat(AwsRedisInstance): add in-transit encryption toggle

---

Makefile
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/sync.sh
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/general
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/list
config/ui-extensions/azureredisinstances/translations

feat: AzureRedisInstance UI

---

.github/workflows/pr-golang-lint.yml
cmd/main.go

chore: log on config reload

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/translations

(feat) added preferredMaintenanceWindow and transitEncryptionEnabled

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/patchAfterMakeManifests.sh
go.mod
go.sum
internal/controller/cloud-control/redisinstance_aws_test.go
internal/controller/cloud-resources/awsredisinstance_test.go
pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/mock/server.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
pkg/kcp/provider/aws/redisinstance/createAuthTokenSecret.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/deleteAuthTokenSecret.go
pkg/kcp/provider/aws/redisinstance/loadAuthTokenSecret.go
pkg/kcp/provider/aws/redisinstance/new.go
pkg/kcp/provider/aws/redisinstance/state.go
pkg/kcp/provider/aws/redisinstance/updateStatus.go
pkg/kcp/provider/aws/redisinstance/util.go
pkg/skr/awsredisinstance/createKcpRedisInstance.go
pkg/testinfra/dsl/awsRedisInstance.go
pkg/testinfra/dsl/redisInstance.go

- adds option to enable auth to aws redis
https://github.com/kyma-project/cloud-manager/issues/434

feat(AwsRedisInstance): add option to enable auth token

---

pkg/kcp/provider/aws/config/config.go
pkg/kcp/provider/aws/config/config_test.go
pkg/kcp/provider/aws/iprange/v1/state.go
pkg/kcp/provider/aws/iprange/v2/state.go
pkg/kcp/provider/aws/nfsinstance/state.go
pkg/kcp/provider/aws/redisinstance/state.go
pkg/kcp/provider/aws/vpcpeering/state.go
pkg/skr/awsnfsvolumebackup/createAwsClient.go

- Separates VPC peering credentials

feat(AwsVpcPeering): peering credentials

---

config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/patchAfterMakeManifests.sh

- Updating the version of gcpnfsvolume, gcpnfsvolumebackup and gcpnfsvolumerestore crds so they get patched on already existing SKRs
- ...
- ...

fix: Updating the versions of SKR CRDs so they get patched

---

pkg/kcp/provider/aws/redisinstance/util.go

chore: lint pkg/kcp/provider/aws/redisinstance/util.go

---

go.mod
pkg/kcp/provider/gcp/client/provider.go

- Used google.golang.org/api/oauth2/v2 package instead of the deprecated JWS package.
https://github.com/kyma-project/cloud-manager/issues/505

fix: linter error for using jws package

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/form
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/form
config/ui-extensions/gcpnfsvolumerestores/cloud-resources.kyma-project.io_gcpnfsvolumerestores_ui.yaml
config/ui-extensions/gcpnfsvolumerestores/form
config/ui-extensions/gcpnfsvolumes/cloud-resources.kyma-project.io_gcpnfsvolumes_ui.yaml
config/ui-extensions/gcpnfsvolumes/form
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/translations
config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/gcpvpcpeerings/form

- added `disableOnEdit` for immutable fields
Resolves #456

(feat) disableOnEdit on immutable fields

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/form
config/ui-extensions/gcpnfsvolumebackups/cloud-resources.kyma-project.io_gcpnfsvolumebackups_ui.yaml
config/ui-extensions/gcpnfsvolumebackups/details
config/ui-extensions/gcpnfsvolumebackups/form
config/ui-extensions/gcpnfsvolumebackups/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/form

(feat) UI Parity 20240822

---

api/cloud-control/v1beta1/nfsinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
internal/controller/cloud-control/nfsinstance_ccee_test.go
pkg/kcp/nfsinstance/copyStatusHostsToHost.go
pkg/kcp/nfsinstance/reconciler.go
pkg/kcp/provider/aws/nfsinstance/updateStatus.go
pkg/kcp/provider/ccee/client/config.go
pkg/kcp/provider/ccee/client/provider.go
pkg/kcp/provider/ccee/config/config.go
pkg/kcp/provider/ccee/config/config_test.go
pkg/kcp/provider/ccee/gardener/infrastructure.go
pkg/kcp/provider/ccee/meta/metadata.go
pkg/kcp/provider/ccee/mock/nfsStore.go
pkg/kcp/provider/ccee/nfsinstance/accessLoad.go
pkg/kcp/provider/ccee/nfsinstance/client/client.go
pkg/kcp/provider/ccee/nfsinstance/new.go
pkg/kcp/provider/ccee/nfsinstance/shareCreate.go
pkg/kcp/provider/ccee/nfsinstance/shareExpandShrink.go
pkg/kcp/provider/ccee/nfsinstance/shareNetworkDelete.go
pkg/kcp/provider/ccee/nfsinstance/shareUpdateStatusCapacity.go
pkg/kcp/provider/ccee/nfsinstance/state.go
pkg/kcp/provider/ccee/nfsinstance/statusDeleting.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
pkg/testinfra/dsl/gcpNfsVolume.go
pkg/testinfra/dsl/nfsInstance.go
tools/dev/README.md
tools/dev/kind/create-all-in-one.sh
tools/dev/kind/kind-all-in-one-config.yaml

feat(NfsInstance): KCP NfsInstance change size

---

.github/workflows/pr-golang-lint.yml
pkg/kcp/provider/azure/mock/server.go
pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
pkg/skr/backupschedule/loadScope_test.go
pkg/skr/backupschedule/removeFinalizer_test.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go

chore: cholang-lint-ci mandatory

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/form
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpvpcpeerings/cloud-resources.kyma-project.io_gcpvpcpeerings_ui.yaml
config/ui-extensions/gcpvpcpeerings/form

- added `disableOnEdit: true` to all immutable boolean fields
Resolves #528

(feat) UI switch disable on edit

---

api/cloud-resources/v1beta1/awsnfsvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups.yaml
config/patchAfterMakeManifests.sh
pkg/skr/awsnfsvolumebackup/createAwsBackup.go
pkg/skr/awsnfsvolumebackup/reconciler.go
pkg/skr/awsnfsvolumebackup/setIdempotencyToken.go
pkg/skr/awsnfsvolumebackup/setIdempotencyToken_test.go

- Idempotent create request
https://github.com/kyma-project/cloud-manager/issues/546

fix(AwsNfsVolumeBackup): Idempotent create request

---

Makefile
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
config/sync.sh
config/ui-extensions/awsnfsvolumebackups/cloud-resources.kyma-project.io_awsnfsvolumebackups_ui.yaml
config/ui-extensions/awsnfsvolumebackups/details
config/ui-extensions/awsnfsvolumebackups/form
config/ui-extensions/awsnfsvolumebackups/general
config/ui-extensions/awsnfsvolumebackups/kustomization.yaml
config/ui-extensions/awsnfsvolumebackups/list
config/ui-extensions/awsnfsvolumebackups/translations

- AWS NFS Volume Backup UI
- ...
- ...
Resolves #552

(feat) AWS NFS Volume Backup UI

---

.github/workflows/cloud-manager-build.yml

- Adds a github action to build the image
https://github.com/kyma-project/test-infra/issues/11759

feat(githubAction) Build image

---

api/cloud-control/v1beta1/vpcpeering_types.go
api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/mock/server.go
pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
pkg/kcp/provider/azure/mock/type.go
pkg/kcp/provider/azure/mock/vpcPeeringStore.go
pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/updateStatus.go
pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
pkg/skr/azurevpcpeering/updateStatus.go

- added status.State that represents the PeeringState of VirtualNetworkPeeringConnection
Resolves #542

feat(AzureVpcPeering): status.State

---

.github/workflows/pr-feature-toggles.yaml
CODEOWNERS
config/featureToggles/featureToggles.yaml

chore: feature flags file

---

api/cloud-control/v1beta1/vpcpeering_types.go
api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/skr/azurevpcpeering/createKpcVpcPeering.go
pkg/testinfra/dsl/kcpVpcPeering.go

- removes AllowVnetAccess
#526

feat(AzureVpcPeering): removes allowVnetAccess

---

.github/workflows/cloud-manager-build.yml

chore(githubAction) Build image

---

api/cloud-control/v1beta1/scope_types.go
config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml

chore: KCP Scope print columns

---

.gitignore
config/featureToggles/.gitignore

chore: adjust gitignore for ff toggle

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/featureToggles/featureToggles.local.yaml
config/patchAfterMakeManifests.sh
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
pkg/kcp/provider/aws/redisinstance/modifyTransitEncryptionEnabled.go
pkg/kcp/provider/aws/redisinstance/new.go
pkg/kcp/provider/aws/redisinstance/state.go
pkg/skr/awsredisinstance/modifyKcpRedisInstance.go
pkg/skr/awsredisinstance/state.go

- Makes `transitEncryptionMode ` mutable.
https://github.com/kyma-project/cloud-manager/issues/572

feat(AwsRedisInstance): make transitEncryptionMode mutable

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/form

- `transitEncryptionEnabled` field is now mutable

(feat) updated AWSredisinstance UI mutable

---

pkg/kcp/provider/aws/config/config.go

chore(AwsVpcPeering): fixes typo in config

---

api/cloud-resources/v1beta1/awsvpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
pkg/kcp/provider/aws/vpcpeering/waitVpcPeeringActive.go
pkg/skr/awsvpcpeering/updateStatus.go

- wait peering connection state active

feat(AwsVpcPeering): wait peering connection active

---

api/cloud-control/v1beta1/vpcpeering_types.go
internal/controller/cloud-control/vpcpeering_azure_test.go

chore(AzureVpcPeering): fixes the race condition

---

docs/user/resources/04-40-10-azure-vpc-peering.md
docs/user/tutorials/01-30-azure-vpc-peering.md

chore(AzureVpcPeering): removes remoteResourceGroup from docs

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/form

(feat) updated awsredisinstances_ui

---

api/cloud-resources/v1beta1/gcpredisinstance_types.go

feat(GcpRedisInstance): implement CloneForPatchStatus method

---

pkg/kcp/provider/aws/config/config.go
pkg/skr/awsnfsvolumebackup/createAwsBackup.go
pkg/skr/awsnfsvolumebackup/state.go

- Updated Aws Backup role to use `AWSBackupDefaultServiceRole`
https://github.com/kyma-project/cloud-manager/issues/460

fix: Aws Backup RoleName

---

api/cloud-control/v1beta1/vpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml

- Adds LocalPeeringName to VpcPeering

feat(VpcPeering): local peering name

---

api/cloud-control/v1beta1/conditions.go
pkg/kcp/provider/aws/redisinstance/addUpdatingCondition.go
pkg/kcp/provider/aws/redisinstance/new.go
pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
pkg/skr/awsredisinstance/updateStatus.go

feat(AwsRedisInstance): show updating state while instance is modified by cloud provider

---

api/cloud-resources/v1beta1/condition.go
pkg/skr/awsredisinstance/updateStatus.go

chore(AwsRedisInstance): add updating condition to skr

---

pkg/kcp/scope/createScopeOpenStack.go

fix(ScopeOpenStack): preserve obj resource version

---

pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go

- Adds warning messages when creating local peering connection.

feat(AzureVpcPeering): warning messages when creating local peering connection

---

docs/user/resources/04-70-aws-redis-instance.md
docs/user/resources/README.md
docs/user/tutorials/01-70-aws-redis-instance.md
docs/user/tutorials/README.md

- Docs for AwsRedisInstance
- Tutorial for AwsRedisInstance
https://github.com/kyma-project/cloud-manager/issues/441

docs(AwsRedisInstance): add resources and tutorial

---

pkg/kcp/provider/gcp/redisinstance/addUpdatingCondition.go
pkg/kcp/provider/gcp/redisinstance/new.go
pkg/skr/gcpredisinstance/updateStatus.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/635

feat(GcpRedisInstance): show updating status while instance is updating

---

internal/controller/cloud-resources/awsvpcpeering_test.go
internal/controller/cloud-resources/azurevpcpeering_test.go
internal/controller/cloud-resources/suite_test.go
pkg/skr/awsvpcpeering/createKcpRemoteNetwork.go
pkg/skr/awsvpcpeering/deleteKcpRemoteNetwork.go
pkg/skr/awsvpcpeering/loadKcpRemoteNetwork.go
pkg/skr/awsvpcpeering/reconciler.go
pkg/skr/awsvpcpeering/state.go
pkg/testinfra/dsl/awsVpcPeering.go

- Adding SKR AwsVpcPeering controller tests

feat(AwsVpcPeering): SKR tests

---

pkg/kcp/provider/gcp/meta/metadata.go
pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go

refactor(RedisInstance): adjust error handling

---

pkg/skr/awsredisinstance/waitKcpStatusUpdate.go
pkg/skr/gcpredisinstance/waitKcpStatusUpdate.go

chore(GcpRedisInstance,AwsRedisInstance): reduce kcp polling frequency

---

docs/user/tutorials/01-60-gcp-redis-instance.md

docs(GcpRedisInstance): update example target redis version

---

.github/workflows/cloud-manager-build.yml

chore: build image on tag

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/details
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/azurevpcpeerings/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/translations

(feat) AzureVPCPeering and GCPRedisInstance UI update

---

pkg/kcp/provider/aws/config/config.go
pkg/skr/awsnfsvolumebackup/state.go

AWS Backup Service Role update

---

api/cloud-resources/v1beta1/awsvpcpeering_types.go
internal/controller/cloud-resources/awsvpcpeering_test.go
pkg/skr/awsvpcpeering/reconciler.go
pkg/skr/awsvpcpeering/updateStatus.go
pkg/skr/awsvpcpeering/waitStatusActive.go

feat(AwsVpcPeering): wait status Active

---

api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
config/patchAfterMakeManifests.sh

chore(AwsNfsBackupSchedule): add category to cloud-resource

---

docs/user/tutorials/01-60-gcp-redis-instance.md
docs/user/tutorials/01-70-aws-redis-instance.md

docs(GcpRedisInstance,AwsRedisInstance): fix tutorial

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/details
config/ui-extensions/awsvpcpeerings/form
config/ui-extensions/awsvpcpeerings/translations
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/details
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/azurevpcpeerings/list
config/ui-extensions/azurevpcpeerings/translations

- AWSVpcPeering has deleteRemotePeering field
- AzureVpcPeering has deleteRemotePeering field

(feat): 20241004 UI parity

---

internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
pkg/skr/backupschedule/calculateOnetimeSchedule.go
pkg/skr/backupschedule/calculateRecurringSchedule.go
pkg/skr/backupschedule/checkCompleted.go
pkg/skr/backupschedule/checkSuspension.go
pkg/skr/backupschedule/compare.go
pkg/skr/backupschedule/createBackup.go
pkg/skr/backupschedule/createBackup_test.go
pkg/skr/backupschedule/deleteBackups.go
pkg/skr/backupschedule/deleteBackups_test.go
pkg/skr/backupschedule/deleteCascade.go
pkg/skr/backupschedule/evaluateNextRun.go
pkg/skr/backupschedule/loadSource.go
pkg/skr/backupschedule/reconciler.go
pkg/skr/backupschedule/removeFinalizer.go
pkg/skr/backupschedule/state.go
pkg/skr/backupschedule/validateTimes.go

- Fix for long running and flaky integration tests.
Fixes #689

test(BackupSchedule): Fix long running and flaky integration tests

---

pkg/kcp/scope/loadKyma.go

fix: do not create Nuke if Scope does not exist

---

api/cloud-control/v1beta1/redisinstance_types.go

feat(RedisInstance): implement CloneForPatchStatus method

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/cloud-resources.kyma-project.io_awsvpcpeerings_ui.yaml
config/ui-extensions/awsvpcpeerings/details
config/ui-extensions/awsvpcpeerings/form
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/details
config/ui-extensions/azurevpcpeerings/form

(feat) disabled deleteRemotePeering field fo Azure and AWS

---

pkg/kcp/provider/azure/iprange/securityGroupLoad.go

fix: Azure IpRange fix log message for security group

---

pkg/kcp/provider/azure/iprange/state.go

fix: Azure IpRange use default creds

---

pkg/kcp/provider/gcp/redisinstance/addUpdatingCondition.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go
pkg/kcp/provider/gcp/redisinstance/new.go
pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
pkg/kcp/provider/gcp/redisinstance/updateRedis.go
pkg/kcp/provider/gcp/redisinstance/updateStatus.go
pkg/kcp/provider/gcp/redisinstance/updateStatusId.go
pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go
pkg/skr/gcpredisinstance/createKcpRedisInstance.go
pkg/skr/gcpredisinstance/deleteAuthSecret.go
pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
pkg/skr/gcpredisinstance/loadAuthSecret.go
pkg/skr/gcpredisinstance/reconciler.go
pkg/skr/gcpredisinstance/updateId.go
pkg/skr/gcpredisinstance/updateStatus.go
pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go

refactor(GcpRedisInstance): use UpdateStatus to PatchStatus

---

internal/api-tests/patch_status_test.go

- added a test that shows that patch status can remove condition

chore: patch status can remove condition

---

pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/709

feat(AwsRedisInstance): set AtRestEncryptionEnabled to true

---

config/featureToggles/featureToggles.yaml

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/596

chore: enable GcpRedisInstance on stage

---

.github/workflows/pr-check-block-via-labels.yaml

chore: block PRs if they have blocking label

---

pkg/kcp/provider/aws/redisinstance/updateStatus.go
pkg/skr/awsredisinstance/modifyAuthSecret.go
pkg/skr/awsredisinstance/reconciler.go
pkg/skr/awsredisinstance/util.go

feat(AwsRedisInstance): update auth secret on data change

---

pkg/kcp/iprange/allocate/allocate.go

- fix for security issue 124386

fix: security issue 124386

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml

- remove transitEncryptionEnabled from AWS RedisInstance
- remove transitEncryptionMode from GCP RedisInstance
- ...

(feat) removed transitEncryptionEnabled and transitEncryptionMode

---

pkg/skr/runtime/looper/runner.go
pkg/testinfra/env.go
pkg/util/string.go
pkg/util/string_test.go

fix: provider in ff context

---

api/cloud-control/v1beta1/redisinstance_types.go
internal/api-tests/kcp_redisinstance_test.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go

fix(RedisInstance): adjust patchstatus for conditions

---

Makefile
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
config/sync.sh
config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
config/ui-extensions/awsnfsbackupschedules/details
config/ui-extensions/awsnfsbackupschedules/form
config/ui-extensions/awsnfsbackupschedules/general
config/ui-extensions/awsnfsbackupschedules/kustomization.yaml
config/ui-extensions/awsnfsbackupschedules/list
config/ui-extensions/awsnfsbackupschedules/translations
config/ui-extensions/awsnfsvolumerestores/cloud-resources.kyma-project.io_awsnfsvolumerestores_ui.yaml
config/ui-extensions/awsnfsvolumerestores/details
config/ui-extensions/awsnfsvolumerestores/form
config/ui-extensions/awsnfsvolumerestores/general
config/ui-extensions/awsnfsvolumerestores/kustomization.yaml
config/ui-extensions/awsnfsvolumerestores/list
config/ui-extensions/awsnfsvolumerestores/translations

- AWS Volume Restores UI
- AWS NFS Backup Schedules UI
- ...

(feat): AWSVolumeRestores &  AWSNFSBackupSchedules UI

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml

- removed enableNonSslPort from List and Detail
- removed zonal-configuration from List and Detail
- ...

(feat) removed enableNonSslPort and zonal-configuration for azureredisinstances

---

api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules.yaml
config/patchAfterMakeManifests.sh

- Removed location attribute from AwsNfsBackupSchedule CR.
Resolves #747

fix(AwsNfsBackupSchedule): Remove location

---

.gitignore
cmd/cli/cmdStatus.go
cmd/cli/cmdStatusPatch.go
cmd/cli/cmdStatusUpdate.go

chore: cli tool status patch and update

---

pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go

chore: print serialized object

---

pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go

This reverts commit d0444941d45ea36a767e25efe498017d4bf1a316.
- ...
- ...
- ...

Revert "chore: print serialized object (#756)"

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/translations

(feat): Redis UI update

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/patchAfterMakeManifests.sh
config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
internal/controller/cloud-control/redisinstance_aws_test.go
internal/controller/cloud-resources/awsredisinstance_test.go
pkg/kcp/provider/aws/redisinstance/client/elastiCacheClient.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/skr/awsredisinstance/createKcpRedisInstance.go
pkg/testinfra/dsl/awsRedisInstance.go
pkg/testinfra/dsl/redisInstance.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/760

feat(AwsRedisInstance): add support for HA via read replicas

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/translations

- `readReplicas` added to AWS Redis Instance UI
- `replicasPerPrimary` removed from Azure Redis Instance UI

(feat) AWS and Azure Redis Instance UI Update

---

api/cloud-resources/v1beta1/awsnfsbackupschedule_types.go

- Fix for the AwsNfsBackupSchedule controller not starting
Part of #539

fix(AwsNfsBackupSchedule): Controller not started

---

internal/controller/cloud-resources/iprange_controller.go
internal/controller/cloud-resources/iprange_test.go
pkg/skr/azureredisinstance/ignorant.go
pkg/skr/iprange/preventDeleteOnAzureRedisInstanceUsage.go
pkg/skr/iprange/reconciler.go
pkg/testinfra/dsl/azureRedisInstance.go
pkg/testinfra/dsl/commonIpRange.go

- refuse to delete ip range if used by Azure Redis instance

feat(AzureRedis): prevent ip range delete when in use by redis

---

pkg/skr/runtime/looper/installer.go

-  fix UI ConfigMap body not copying over

(fix): fix UI ConfigMap body not copying over

---

pkg/skr/runtime/looper/installer.go

(fix) fixed error where it was trying to copy "body" field instead of "data"

---

api/cloud-resources/v1beta1/awsvpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsvpcpeerings.yaml
config/patchAfterMakeManifests.sh

- Adding State as printable column for AwsVpcPeering

chore(AwsVpcPeering): adds State as printable column

---

pkg/kcp/provider/gcp/redisinstance/createRedis.go

fix(GcpRedisInstance): pass replicaCount to google API

---

internal/api-tests/kcp_redisinstance_gcp_test.go

test(RedisInstance): add KCP GCP API tests

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/translations

- added `replicaPerPrimary` for Azure Redis Instance
- added `replicaCount` fo GCP Redis Instance
- ...

(feat) Added replica support for Azure and GCP Redis Instance

---

config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/translations

- removed `memorySizeGb`
- removed `tier`
- added `redisTier`
- `replicaCount` no longer immutable

(feat): updated gcp redis instances with tier abstraction

---

docs/user/resources/04-70-aws-redis-instance.md
docs/user/tutorials/01-70-aws-redis-instance.md

docs(AwsRedisInstance): add redisTier details

---

docs/user/resources/04-80-azure-redis-instance.md

- remove replicasPerPrimary
- replace SKU.Capacity with redisTier

docs(AzureRedis): remove replicas, replace sku.capacity with redisTier

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/translations

- removed `readReplicas` and `replicasPerPrimary` from AWS and Azure Redis Instances respectively
- removed `cacheNodeType` from AWS Redis Instances
- added `redisTier` to AWS and Azure Redis Instances

(feat): Redis Instance UI Update

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go

- Allows VpcPeering to be deleted if local Network is missing

feat(AzureVpcPeering): allows VpcPeering to be deleted if local Network is missing

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml

fix: fixed bug where kustomize was adding extra |2 to the manifest

---

api/cloud-control/v1beta1/redisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
internal/api-tests/kcp_redisinstance_test.go

feat(RedisInstance): add API validator to ensure IpRange is defined

---

pkg/kcp/nuke/reconciler.go
pkg/kcp/nuke/shortCircuitCompleted.go
pkg/kcp/nuke/statusCompleted.go

feat(Nuke): StopAndForget Completed Nukes

---

pkg/common/actions/removeFinalizer.go

- added log entry for finalizer removal so we could better diagnose deprovisioning issue from the logs

chore: log finalizer removal

---

pkg/kcp/provider/gcp/nfsinstance/new.go

chore(NfsInstance, GCP): add logs to factory

---

pkg/kcp/provider/aws/redisinstance/updateStatus.go
pkg/kcp/provider/azure/redisinstance/updateStatus.go
pkg/kcp/provider/gcp/redisinstance/updateStatus.go

fix(RedisInstance): stop KCP loop due to status update

---

internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
pkg/skr/backupschedule/calculateOnetimeSchedule.go
pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
pkg/skr/backupschedule/evaluateNextRun.go
pkg/testinfra/dsl/nfsBackupSchedule.go

fix(NfsBackupSchedule): continuous looping of the one-time schedule

---

pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go

test(RedisInstance): handle canceled context in cloud provider fakes

---

pkg/kcp/network/preventDeleteWhenUsedByIpRange.go

chore(Network): fix error msg

---

.github/workflows/cloud-manager-build.yml

Changes:
- split image build into steps
- one step for building PRs
- second step for building the main and tags
Names and conditions could be better. Please advise.

chore: splits image build into steps

---

cmd/main.go
config/config/vpcpeering.yaml
pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
pkg/kcp/provider/aws/vpcpeering/kcpNetworkLocalLoad.go
pkg/kcp/provider/aws/vpcpeering/kcpNetworkRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
pkg/kcp/provider/azure/vpcpeering/kcpNetworkRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go
pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
pkg/kcp/vpcpeering/config/config.go

chore: VpcPeering config

---

pkg/skr/awsredisinstance/modifyKcpRedisInstance.go

chore(AwsRedisInstance): update error msg

---

internal/controller/cloud-control/vpcpeering_azure_test.go

- fixes race condition in tests

chore: fixes race condition in tests

---

pkg/kcp/provider/gcp/vpcpeering/waitRemoteVpcPeeringAvailable.go
pkg/kcp/provider/gcp/vpcpeering/waitVpcPeeringActive.go

feat(GcpVpcPeering): print current state during wait

---

sec-scanners-config.yaml

release 1.2.1

---

pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go

- fixes deletion issues when SPN is unauthorized

fix(AzureVpcPeering): fixes deletion issues when SPN is unauthorized

---

sec-scanners-config.yaml

sec scan 1.2.2

---

api/cloud-control/v1beta1/vpcpeering_types.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/mock/networkStore.go
pkg/kcp/provider/azure/mock/type.go
pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go

- fixes deletion issues when Kyma SPN is unauthorized in remote subscription
- adds peering loading fail-over
- relaxes reconciler requeuing on Unauthorized errors

fix(AzureVpcPeering): fixes deletion issues when Kyma SPN is unauthorized

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/translations

feat: removed shardCount from AzureRedisInstance UI

---

docs/user/resources/README.md

- Remove the ToC as it did not render ok at kyma-project.io

docs: Remove the toc

---

pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go

- relaxes authorization error requeue
- allows user to recover

fix(AwsVpcPeering): relaxes authorization error requeue

---

.github/ISSUE_TEMPLATE/cm-permissions.yaml

chore: gh issue template permission change

---

pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go

refactor(GcpRedisInstance): handle NotFound in action instead of client

---

.github/workflows/pr-checks.yml
config/featureToggles/featureToggles.yaml
internal/controller/cloud-control/nuke_gcp_test.go
pkg/composed/predicate.go
pkg/feature/ffNukeBackupsGcp.go
pkg/kcp/nuke/reconciler.go

FF Issue #873 
- ...
- ...
- ...

chore: feature flag nukeBackupsGcp

---

.checkmarx/config.yml
.github/workflows/merge-gate.yaml
internal/controller/cloud-resources/iprange_test.go
pkg/testinfra/dsl/gomega.go

- added merge-gate workflow and check 
- added testinfra/dsl/SucceedIgnoreNotFound matcher
- modified flaky test failure in `internal/controller/cloud-resources/iprange_test.go` cleanups to use new `SucceedIgnoreNotFound` matcher
- added checkmarkx config to try to ignore `pkg/testinfra` and `cmd/cli` dirs

chore: merge gate

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-control/v1beta1/types.go
internal/controller/cloud-control/redisinstance_aws_test.go
internal/controller/cloud-control/redisinstance_gcp_test.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/removeReadyCondition.go
pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/updateStatus.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go
pkg/kcp/provider/gcp/redisinstance/new.go
pkg/kcp/provider/gcp/redisinstance/removeReadyCondition.go
pkg/kcp/provider/gcp/redisinstance/updateStatus.go
pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/881

chore(RedisInstance): use .status.state (GCP, AWS)

---

.github/workflows/merge-gate.yaml

chore: run merge-gate on pr label change

---

docs/user/resources/04-30-30-azure-vpc-peering.md
docs/user/tutorials/01-30-30-azure-vpc-peering.md

- adds limitation so that only networks on the same tenant can be peered
- update tutorial to use stage Azure service principal

docs(AzureVpcPeering): updating documentation

---

internal/controller/cloud-resources/iprange_test.go

chore(IpRange): fix flaky test

---

renovate.json

chore: renovate config

---

pkg/kcp/scope/loadScopeObj.go
pkg/kcp/scope/logScope.go
pkg/kcp/scope/reconciler.go

chore: remove scope logs when no action is executed

---

pkg/kcp/provider/aws/redisinstance/createParameterGroup.go
pkg/kcp/provider/aws/redisinstance/deleteParameterGroup.go
pkg/kcp/provider/aws/redisinstance/modifyParameterGroup.go
pkg/kcp/provider/aws/redisinstance/new.go

- creation, deletion, and modification of ParameterGroups is now done via generic method
- this is a necessary intermediate step for eventual resolution of https://github.com/kyma-project/cloud-manager/issues/939
https://github.com/kyma-project/cloud-manager/issues/939

refactor(AwsRedisInstance): generic functions for param group management

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/details
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml
config/ui-extensions/awsredisinstances/translations
config/ui-extensions/azureredisinstances/cloud-resources.kyma-project.io_azureredisinstances_ui.yaml
config/ui-extensions/azureredisinstances/details
config/ui-extensions/azureredisinstances/form
config/ui-extensions/azureredisinstances/kustomization.yaml
config/ui-extensions/azureredisinstances/translations
config/ui-extensions/gcpredisinstances/cloud-resources.kyma-project.io_gcpredisinstances_ui.yaml
config/ui-extensions/gcpredisinstances/details
config/ui-extensions/gcpredisinstances/form
config/ui-extensions/gcpredisinstances/kustomization.yaml
config/ui-extensions/gcpredisinstances/translations

- added extraData for AWS Redis Instance
- added extraData for Azure Redis Instance
- added extraData for GCP Redis Instance

feat(RedisInstance UI) handle extraData UI

---

config/crd/bases/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances.yaml
config/patchAfterMakeManifests.sh

chore(AwsRedisInstance): up manifest version

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/cloud-resources.kyma-project.io_awsredisinstances_ui.yaml
config/ui-extensions/awsredisinstances/form
config/ui-extensions/awsredisinstances/kustomization.yaml

feat: added warning to AWS Redis Instance Engine Version

---

api/cloud-control/v1beta1/skrstatus_types.go

fixed SkrStatus clone for patch with labels and annotations

---

pkg/composed/action.go
pkg/composed/conditions.go
pkg/skr/iprange/loadKcpIpRange.go
pkg/skr/iprange/updateId.go
pkg/skr/iprange/updateStatus.go

chore: reduce logs for skr iprange

---

pkg/composed/bridge.go

chore: log reconciliation outcome

---

api/cloud-control/v1beta1/skrstatus_types.go
config/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_skrstatuses.yaml

chore: made SkrStatus spec.conditions optional

---

.checkmarx/config.yml

chore: remove obsolete/non-working cx config

---

config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/cloud-resources.kyma-project.io_azurevpcpeerings_ui.yaml
config/ui-extensions/azurevpcpeerings/details
config/ui-extensions/azurevpcpeerings/form
config/ui-extensions/azurevpcpeerings/kustomization.yaml
config/ui-extensions/azurevpcpeerings/list
config/ui-extensions/azurevpcpeerings/translations

feat: removed unused fields from Azure VPC Peering UI

---

pkg/migrateFinalizers/migrator.go
pkg/migrateFinalizers/runner.go

chore: more logs on finalizer migration

---

internal/controller/cloud-control/rediscluster_controller.go
pkg/kcp/provider/aws/rediscluster/new.go
pkg/kcp/provider/aws/rediscluster/state.go
pkg/kcp/provider/azure/rediscluster/new.go
pkg/kcp/provider/azure/rediscluster/state.go
pkg/kcp/provider/gcp/rediscluster/new.go
pkg/kcp/provider/gcp/rediscluster/state.go
pkg/kcp/rediscluster/reconciler.go

feat(RedisCluster): add cloud provider boilereplate

---

pkg/skr/backupschedule/calculateRecurringSchedule_test.go

- Fix for the cron expression unit test timing issue.
Fixes #https://github.tools.sap/kyma/cloud-manager-infra/issues/11

fix(BackupSchedule): cron schedule unit test timing issue

---

cmd/main.go
internal/controller/cloud-control/redisinstance_controller.go
pkg/kcp/provider/aws/client/elastiCacheClient.go
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/mock/server.go
pkg/kcp/provider/aws/mock/type.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/state.go
pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go

refactor(RedisInstance): move aws client to common package

---

internal/controller/cloud-control/vpcpeering_aws_test.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/composed/state.go
pkg/migrateFinalizers/successHandler.go
pkg/migrateFinalizers/tests/migrate_finalizers_test.go

chore: migrate finalizer repeat 3 times

---

pkg/kcp/provider/aws/client/elastiCacheClient.go
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go

chore(AwsRedisInstance): add shardcount to client

---

docs/user/00-20-nfs.md
docs/user/00-30-vpc-peering.md
docs/user/00-40-redis.md
docs/user/00-50-vpc-peering-authorization.md
docs/user/README.md
docs/user/resources/README.md

- Synced OS docu with Help Portal docu

docs: Sync OS docu with Help Portal docu

---

config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/ui-extensions/awsnfsbackupschedules/cloud-resources.kyma-project.io_awsnfsbackupschedules_ui.yaml
config/ui-extensions/awsnfsbackupschedules/kustomization.yaml
config/ui-extensions/gcpnfsbackupschedules/cloud-resources.kyma-project.io_gcpnfsbackupschedules_ui.yaml
config/ui-extensions/gcpnfsbackupschedules/kustomization.yaml

- Increment the UI version to show the UI changes.
Part of https://github.tools.sap/kyma/cloud-manager-infra/issues/28

fix(BackupSchedule): Incremented UI ConfigMap version

---

pkg/skr/azurerwxvolumebackup/client/protectionPolicies.go
pkg/skr/azurerwxvolumebackup/client/recoveryPoint.go
pkg/skr/azurerwxvolumebackup/client/vault.go

feat: Azure Client Implementation

---

pkg/skr/azurerwxvolumebackup/client/client.go
pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/client/jobs.go
pkg/skr/azurerwxvolumebackup/client/restore.go

- Added client methods for AzureRwxVolumeRestore
See also #964

feat: AzureRwxVolumeRestore client

---

internal/controller/cloud-resources/azurerwxbackupschedule_controller.go
pkg/skr/backupschedule/backupImpl.go
pkg/skr/backupschedule/backupImplAzureRwx.go

- AzureRwxBackupSchedule reconciler 
See also #965

chore(AzureRwxBackupSchedule): reconciler implementation

---

pkg/skr/azurerwxvolumebackup/client/backup.go
pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/client/protectionPolicies.go
pkg/skr/azurerwxvolumebackup/client/vault.go

feat: Azure Client handling Poller response

---

pkg/skr/azurerwxvolumebackup/client/backupProtectableItems.go
pkg/skr/azurerwxvolumebackup/client/client.go
pkg/skr/azurerwxvolumebackup/client/protectedItems.go

feat: created BackupProtectableItemsClient and ProtectedItemsClient

---

internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
internal/controller/cloud-resources/azure/azurerwxbackupschedule_test.go
internal/controller/cloud-resources/azure/suite_test.go
internal/controller/cloud-resources/gcpnfsbackupschedule_test.go
internal/controller/cloud-resources/suite_test.go
pkg/skr/backupschedule/backupImpl.go
pkg/skr/backupschedule/backupImplAwsNfs.go
pkg/skr/backupschedule/backupImplAzureRwx.go
pkg/skr/backupschedule/backupImplGcpNfs.go
pkg/skr/backupschedule/loadSource.go
pkg/testinfra/dsl/azureRwxVolume.go
pkg/testinfra/dsl/azureRwxVolumeBackup.go
pkg/testinfra/dsl/nfsBackupSchedule.go
pkg/testinfra/dsl/scope.go

- Integration tests for AzureRwxBackupSchedule
See also #965

test: Azure RWX backup schedule

---

api/cloud-resources/v1beta1/azurerwxvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml

(feat) added storage account path for Azure RWX Backups Status field

---

Makefile
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxbackupschedules_ui.yaml
config/sync.sh
config/ui-extensions/azurerwxbackupschedules/cloud-resources.kyma-project.io_azurerwxbackupschedules_ui.yaml
config/ui-extensions/azurerwxbackupschedules/details
config/ui-extensions/azurerwxbackupschedules/form
config/ui-extensions/azurerwxbackupschedules/general
config/ui-extensions/azurerwxbackupschedules/kustomization.yaml
config/ui-extensions/azurerwxbackupschedules/list
config/ui-extensions/azurerwxbackupschedules/translations

- UI for Azure RWX Backup Schedule
See also #974

feat: Azure RWX Backup Schedule UI

---

api/cloud-resources/v1beta1/azurerwxbackupschedule_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurerwxbackupschedules.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxbackupschedules.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxbackupschedules_ui.yaml
config/patchAfterMakeManifests.sh
config/ui-extensions/azurerwxbackupschedules/cloud-resources.kyma-project.io_azurerwxbackupschedules_ui.yaml
config/ui-extensions/azurerwxbackupschedules/details
config/ui-extensions/azurerwxbackupschedules/form
config/ui-extensions/azurerwxbackupschedules/kustomization.yaml
config/ui-extensions/azurerwxbackupschedules/translations
pkg/skr/backupschedule/backupImplAzureRwx.go

- Added location to the AzureRwxBackupSchedule spec.
See also #965

chore(AzureRwxBackupSchedule): Added location

---

.github/workflows/pr-checks.yml
.github/workflows/pr-golang-lint.yml
pkg/composed/v2/action.go
pkg/composed/v2/action_test.go
pkg/composed/v2/bridge.go
pkg/composed/v2/conditions.go
pkg/composed/v2/errors.go
pkg/composed/v2/flow.go
pkg/composed/v2/logger.go
pkg/composed/v2/markedForDeletionPredicate.go
pkg/composed/v2/predicate.go
pkg/composed/v2/predicate_test.go
pkg/composed/v2/state.go
pkg/k8sport/annotateObj.go
pkg/k8sport/createObj.go
pkg/k8sport/ctx.go
pkg/k8sport/deleteObj.go
pkg/k8sport/eventPort.go
pkg/k8sport/fake/k8sFakePort.go
pkg/k8sport/fake/k8sFakePort_test.go
pkg/k8sport/labelObj.go
pkg/k8sport/loadObj.go
pkg/k8sport/port.go
pkg/util/clone.go
pkg/util/ctx.go

- new version of the composed package where state holds no services, but only data, so it's easier to mock it
- services, like k8s client, are refactored out of the state into the "ports"

chore: composed v2

---

api/cloud-resources/v1beta1/azurerwxvolumerestore_types.go
pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/client/jobsMock.go
pkg/skr/azurerwxvolumebackup/client/restoreMock.go
pkg/skr/azurerwxvolumerestore/checkRestoreJob.go
pkg/skr/azurerwxvolumerestore/checkRestoreJob_test.go
pkg/skr/azurerwxvolumerestore/reconciler.go
pkg/skr/azurerwxvolumerestore/startAzureRestore.go
pkg/skr/azurerwxvolumerestore/startAzureRestore_test.go

- completing the implementation of AzureRwxVolumeRestore reconciler 
See also #964

feat: AzureRwxVolumeRestore reconciler

---

api/cloud-resources/v1beta1/azurerwxvolumebackup_types.go
internal/controller/cloud-resources/azurerwxvolumebackup_controller.go
pkg/skr/azurerwxvolumebackup/client/backupProtectedItems.go
pkg/skr/azurerwxvolumebackup/client/client.go
pkg/skr/azurerwxvolumebackup/client/mock.go
pkg/skr/azurerwxvolumebackup/createBackup.go
pkg/skr/azurerwxvolumebackup/createClient.go
pkg/skr/azurerwxvolumebackup/createVault.go
pkg/skr/azurerwxvolumebackup/loadPersistentVolume.go
pkg/skr/azurerwxvolumebackup/loadPersistentVolumeClaim.go
pkg/skr/azurerwxvolumebackup/reconciler.go
pkg/skr/azurerwxvolumebackup/state.go

feat:  AzureRwxBackup

---

docs/user/resources/04-40-10-aws-redis-instance.md

docs(AwsRedisInstance): remove obsolete readReplicas field

---

docs/user/00-20-nfs.md
docs/user/00-25-scheduling-best-practices.md
docs/user/00-30-vpc-peering.md
docs/user/00-31-vpc-peering-authorization.md
docs/user/00-40-redis.md
docs/user/00-50-vpc-peering-authorization.md
docs/user/README.md
docs/user/_sidebar.md
docs/user/resources/README.md
docs/user/tutorials/01-20-11-aws-nfs-volume-backup.md
docs/user/tutorials/01-20-12-aws-scheduled-nfs-backup.md
docs/user/tutorials/01-20-13-aws-nfs-volume-restore.md
docs/user/tutorials/01-20-21-gcp-nfs-volume-backup.md
docs/user/tutorials/01-20-22-gcp-scheduled-nfs-backup.md
docs/user/tutorials/01-20-23-gcp-nfs-volume-restore.md
docs/user/tutorials/01-30-10-aws-vpc-peering.md
docs/user/tutorials/01-30-20-gcp-vpc-peering.md
docs/user/tutorials/01-30-30-azure-vpc-peering.md
docs/user/tutorials/README.md

- Syned OS version with the changes made in Help Portal documentation while removing the internal classification from the Cloud Manager module docu topics 

docs: Sync DITA and OS content

---

docs/user/tutorials/01-40-10-aws-redis-instance.md

docs: Update 01-40-10-aws-redis-instance.md

---

docs/user/00-31-vpc-peering-authorization.md
docs/user/tutorials/01-30-20-gcp-vpc-peering.md

docs: Adjust formatting

---

sec-scanners-config.yaml

Update sec-scanners-config.yaml -add 1.2.5 to scanned images

---

api/cloud-resources/v1beta1/azurerwxvolumebackup_types.go
pkg/skr/azurerwxvolumebackup/client/backupMock.go
pkg/skr/azurerwxvolumebackup/client/backupProtectableItemsMock.go
pkg/skr/azurerwxvolumebackup/client/backupProtectedItemsMock.go
pkg/skr/azurerwxvolumebackup/client/constants_test.go
pkg/skr/azurerwxvolumebackup/client/mock.go
pkg/skr/azurerwxvolumebackup/client/protectedItemsMock.go
pkg/skr/azurerwxvolumebackup/client/protectionPoliciesMock.go
pkg/skr/azurerwxvolumebackup/client/vaultMock.go
pkg/skr/azurerwxvolumebackup/createBackup.go
pkg/skr/azurerwxvolumebackup/createBackup_test.go
pkg/skr/azurerwxvolumebackup/createVault.go
pkg/skr/azurerwxvolumebackup/createVault_test.go
pkg/skr/azurerwxvolumebackup/reconciler.go

test: AzureRwxVolumeBackup createVault and createBackup UT

---

internal/controller/cloud-resources/iprange_controller.go

fix: ensure casting succeeded in iprange_controller

---

Makefile
api/cloud-resources/v1beta1/azurerwxvolumerestore_types.go
cmd/main.go
config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumerestores_ui.yaml
config/sync.sh
config/ui-extensions/azurerwxvolumerestores/cloud-resources.kyma-project.io_azurerwxvolumerestores_ui.yaml
config/ui-extensions/azurerwxvolumerestores/details
config/ui-extensions/azurerwxvolumerestores/form
config/ui-extensions/azurerwxvolumerestores/general
config/ui-extensions/azurerwxvolumerestores/kustomization.yaml
config/ui-extensions/azurerwxvolumerestores/list
config/ui-extensions/azurerwxvolumerestores/translations

- UI for AzureRwxVolumeRestore
- Setting up AzureRwxVolumeRestore reconciler in main executable
Fixes #972

feat: Azure Rwx Volume Restore UI

---

pkg/kcp/provider/ccee/config/config.go

fix: ccee config fix

---

cmd/main.go

feat: ccee nfs

---

config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumerestores.yaml
config/patchAfterMakeManifests.sh

- Bumping version so that startTime in status gets added to the schema
See also #964

fix: AzureRwxVolumeRestore schema fix

---

docs/contributor/azure-permissions.md

…d Restore
- Adding roles requested in https://github.tools.sap/kyma/backlog/issues/7043
- ...
- ...

chore: added roles to Default Principal required for AzureRwxVolumeBackup

---

pkg/kcp/scope/logScope.go
pkg/kcp/scope/nukeCreate.go
pkg/kcp/scope/reconciler.go

fix: scope create nuke

---

pkg/skr/azurerwxvolumebackup/client/restore.go
pkg/skr/azurerwxvolumebackup/client/vault.go

- Fix log messages in vault and restore clients
See also #964 
See also #963

fix: AzureRwxVolumeBackup/Restore vault/restore clients log messages

---

pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/client/constants_test.go
pkg/skr/azurerwxvolumerestore/checkRestoreJob.go
pkg/skr/azurerwxvolumerestore/findAzureRestoreJob.go

- Noticed in testing that AzureStorageErrorInfo can have special characters causing logging issues. To make logs escape all special characters while keep it readable, used json instead of building pretty string. 
See also #964

fix: AzureRwxVolumeRestore AzureStorageErrorInfo proper log messaging

---

pkg/kcp/provider/gcp/rediscluster/reconcile.go
pkg/kcp/provider/gcp/subnet/reconcile.go
pkg/kcp/rediscluster/reconciler.go
pkg/kcp/redisinstance/reconciler.go

chore: add missing feature.LoadFeatureContextFromObj calls

---

internal/controller/cloud-control/iprange_controller.go
internal/controller/cloud-control/iprange_delete_test.go
pkg/kcp/iprange/preventDeleteOnRedisClusterUsage.go
pkg/kcp/iprange/reconciler.go

chore(cloud-control): prevent IpRange delete if used by RedisCluster

---

pkg/kcp/scope/nukeCreate.go
pkg/kcp/scope/nukeLoad.go
pkg/kcp/scope/nukeWaitCompleted.go
pkg/kcp/scope/reconciler.go
pkg/kcp/scope/state.go

- create Nuke and wait until completed before deleting the Scope

fix: scope nuke create

---

pkg/composed/conditions.go
pkg/composed/errors.go
pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
pkg/kcp/provider/aws/vpcpeering/createRoutes.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/waitPendingAcceptance.go
pkg/skr/awsvpcpeering/updateStatus.go
tools/dev/README.md

- status not updated when condition is removed. composed.AnyConditionChanged does not detect removed conditions therefore it is replaced with composed.SyncConditions
- improved logging when creating routes
- logs VPC peering connection status changes
- detect unauthorized errors while loading remote VPC network or peering connection

chore(AwsVpcPeering): refactoring

---

cmd/main.go
internal/controller/cloud-control/gcpsubnet_controller.go
internal/controller/cloud-control/subnet_delete_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/gcp/subnet/preventDeleteOnRedisClusterUsage.go
pkg/kcp/provider/gcp/subnet/reconcile.go

chore(cloud-control): halt gcpsubnet delete when used

---

internal/controller/cloud-control/gcprediscluster_test.go
internal/controller/cloud-control/nuke_gcp_test.go
pkg/kcp/nuke/loadResources.go

- adds `RedisCluster`, `GcpRedisCluster`, and `GcpSubnet` resources to Nukable resource list
- refactors Gcp Nuke Test

chore(cloud-control): add missing resources to Nuke

---

pkg/skr/azurerwxvolumebackup/createBackup_test.go
pkg/skr/azurerwxvolumebackup/reconciler.go
pkg/skr/azurerwxvolumebackup/state.go

chore: refactored azure backup to use commonscope

---

pkg/skr/runtime/manager/manager.go

- set custom cache DefaultWatchErrorHandler that ignores DeadlineExceeded and Canceled errors to prevent SKR Looper deadline reflector logs, ie `"Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1beta1.GcpRedisInstance: context deadline exceeded" logger="UnhandledError"`

chore: skr looper prevent deadline reflector logs

---

cmd/main.go
pkg/kcp/kyma/skrActivate.go
pkg/kcp/kyma/skrDeactivate.go
pkg/kcp/scope/skrDeactivate.go
pkg/skr/runtime/looper/skrLooper.go
pkg/testinfra/run.go

- removed log entries from the kyma and scope flow 
- refactored SkrCollection to log only when really starting or stopping trough logger from the context argument

chore: reduce unnecessary logging for starting/stopping SKR

---

pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/createBackupPolicy.go
pkg/skr/azurerwxvolumebackup/protectFileshare.go

chore: changed DefaultPolicyName to be `cm-noop-policy`

---

api/cloud-resources/v1beta1/azurerwxvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurerwxvolumebackups.yaml

chore: added categories to azure backup CR

---

cmd/main.go
docs/contributor/gcp-permissions.md
go.mod
go.sum
internal/controller/cloud-control/scope_controller.go
internal/controller/cloud-control/scope_gcp_test.go
internal/controller/cloud-control/suite_test.go
pkg/config/README.md
pkg/config/binding.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/client/tokenProvider.go
pkg/kcp/provider/gcp/exposedData/addressesLoad.go
pkg/kcp/provider/gcp/exposedData/client/client.go
pkg/kcp/provider/gcp/exposedData/exposedDataSetToScope.go
pkg/kcp/provider/gcp/exposedData/new.go
pkg/kcp/provider/gcp/exposedData/routersLoad.go
pkg/kcp/provider/gcp/exposedData/state.go
pkg/kcp/provider/gcp/meta/metadata.go
pkg/kcp/provider/gcp/mock/exposedDataStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/scope/reconciler.go
pkg/testinfra/dsl/gcpGardenerCloud.go
pkg/testinfra/dsl/shoot.go
pkg/util/must.go

feat: GCP expose nat gateway ip

---

go.mod
internal/controller/cloud-control/scope_aws_test.go
internal/controller/cloud-control/scope_azure_test.go
internal/controller/cloud-control/scope_gcp_test.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/client/tokenProvider.go
pkg/kcp/provider/gcp/exposedData/client/client.go
pkg/kcp/scope/exposedDataSaveToScope.go
pkg/kcp/scope/exposedDataSaveToSkr.go
pkg/kcp/scope/reconciler.go
pkg/skr/runtime/manager/factory.go
pkg/testinfra/dsl/gardenerCluster.go
pkg/testinfra/dsl/kyma.go
pkg/testinfra/dsl/objActions.go

feat: exposed nat gateway ip write to skr

---

cmd/main.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/client/tokenProvider.go

chore: gcp clients debug

---

pkg/testinfra/dsl/nfsBackupSchedule.go

- Fix for the intermittent failures of backup schedule integration tests.
See also #1235

fix: Intermittent failure of backup schedule tests

---

internal/controller/cloud-resources/gcpnfsbackupschedule_test.go

chore: disable SKR GcpNfsBackupSchedule controller tests

---

internal/controller/cloud-resources/aws/awsnfsbackupschedule_test.go
internal/controller/cloud-resources/azure/azurerwxbackupschedule_test.go
internal/controller/cloud-resources/gcpnfsbackupschedule_test.go

- Fix for the intermittent failure on the NfsBackupSchedule integration tests
See also #1235

fix: Intermittent failure of Backup Schedule integration test

---

cmd/main.go
internal/controller/cloud-control/gcpsubnet_controller.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/subnet/client/computeClient.go
pkg/kcp/provider/gcp/subnet/client/networkConnectivityClient.go
pkg/kcp/provider/gcp/subnet/state.go

- use gcpclient.GcpClientProvider to obtain clients in cloud-control GcpSubnet

refactor(cloud-control): use gcpclient.GcpClientProvider in GcpSubnet

---

Makefile
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpsubnets_ui.yaml
config/sync.sh
config/ui-extensions/gcpsubnets/cloud-resources.kyma-project.io_gcpsubnets_ui.yaml
config/ui-extensions/gcpsubnets/details
config/ui-extensions/gcpsubnets/form
config/ui-extensions/gcpsubnets/general
config/ui-extensions/gcpsubnets/kustomization.yaml
config/ui-extensions/gcpsubnets/list
config/ui-extensions/gcpsubnets/translations
pkg/skr/runtime/looper/installer_test.go

feat: GCP Subnet UI

---

pkg/kcp/provider/aws/client/elastiCacheClient.go
pkg/kcp/provider/aws/mock/elastiCacheClientFake.go
pkg/kcp/provider/aws/rediscluster/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go

refactor(cloud-control): move business logic out of elasticache client

---

pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/updateStatusId.go

- Fix for updating the `status.id` attribute if it gets over-written
Related to https://github.com/kyma-project/cloud-manager/pull/1280

fix(GcpNfsVolume): failing integration test with JSON patch

---

docs/user/resources/04-50-10-aws-redis-cluster.md
docs/user/tutorials/01-50-10-aws-redis-cluster.md

docs(AwsRedisCluster): add docs and tutorial

---

docs/user/resources/40-50-20-gcp-redis-cluster.md
docs/user/tutorials/01-50-20-gcp-redis-cluster.md

docs(GcpRedisCluster): add docs and tutorial

---

internal/controller/cloud-resources/gcpsubnet_test.go
pkg/skr/gcpsubnet/createKcpGcpSubnet.go

fix(GcpSubnet): use correct network name

---

sec-scanners-config.yaml

(chore) scan tag 1.3.0

---

sec-scanners-config.yaml

add rc-tag: 1.3.0

---

pkg/skr/common/defaultgcpsubnet/createDefaultSkrGcpSubnet.go

chore: change default GcpSubnet CIDR

---

pkg/kcp/provider/azure/meta/metadata.go

- log AzureVpcDnsLink errors
fixes #1355

chore(AzureVpcDnsLink): log errors

---

pkg/kcp/provider/azure/mock/storageStore.go
pkg/skr/azurerwxvolumebackup/client/recoveryPoint.go

chore: replace panic with error in azure mocked client library

---

Dockerfile
go.mod

chore: update golang (1.24.5 -> 1.24.6)

---

Makefile
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcdnslinks_ui.yaml
config/sync.sh
config/ui-extensions/azurevpcdnslinks/cloud-resources.kyma-project.io_azurevpcdnslinks_ui.yaml
config/ui-extensions/azurevpcdnslinks/details
config/ui-extensions/azurevpcdnslinks/form
config/ui-extensions/azurevpcdnslinks/general
config/ui-extensions/azurevpcdnslinks/kustomization.yaml
config/ui-extensions/azurevpcdnslinks/list
config/ui-extensions/azurevpcdnslinks/translations
pkg/skr/runtime/looper/installer_test.go

feature: AzureVpcDnsLink UI

---

sec-scanners-config-release.yaml

chore: added sec-scanners-config-release.yaml

---

cmd/main.go
internal/controller/cloud-control/scope_controller.go
internal/controller/cloud-control/scope_sap_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/sap/exposedData/client/client.go
pkg/kcp/provider/sap/exposedData/exposedDataSetToScope.go
pkg/kcp/provider/sap/exposedData/new.go
pkg/kcp/provider/sap/exposedData/routerLoad.go
pkg/kcp/provider/sap/exposedData/state.go
pkg/kcp/provider/sap/mock/nfsStore.go
pkg/kcp/provider/sap/mock/server.go
pkg/kcp/provider/sap/mock/types.go
pkg/kcp/provider/sap/nfsinstance/client/client.go
pkg/kcp/scope/reconciler.go
pkg/testinfra/dsl/sapGardenerCloud.go
pkg/testinfra/dsl/shoot.go

feat: expose egress ip for SAP CCEE

---

docs/user/resources/04-40-10-aws-redis-instance.md
docs/user/resources/04-40-20-gcp-redis-instance.md
docs/user/resources/04-40-30-azure-redis-instance.md
docs/user/resources/04-50-10-aws-redis-cluster.md
docs/user/resources/04-50-30-azure-redis-cluster.md

- fixed bad formatted md not valid in Vitepress (markdown-it)
- 
https://github.com/kyma-project/kyma/pull/18817

fixed bad formatted md not valid in Vitepress (markdown-it)

---

pkg/kcp/provider/sap/nfsinstance/client/client.go

fix: sap ccloud manila allow access microversion fix

---

pkg/kcp/provider/sap/nfsinstance/client/client.go

fix: ccee list access

---

internal/controller/cloud-control/nfsinstance_ccee_test.go
pkg/kcp/provider/sap/mock/nfsStore.go
pkg/kcp/provider/sap/nfsinstance/client/client.go
pkg/kcp/provider/sap/nfsinstance/shareExportRead.go
pkg/kcp/provider/sap/nfsinstance/shareExportRead_test.go
pkg/kcp/provider/sap/nfsinstance/shareNetworkDelete.go
pkg/kcp/provider/sap/nfsinstance/state.go
pkg/skr/sapnfsvolume/pv_create.go

fix: ccee list access & export locations

---

internal/controller/cloud-resources/gcpsubnet_test.go
pkg/skr/gcpsubnet/reconciler.go

fix: add finalizer on first step of gcpsubnet creation

---

docs/user/resources/04-40-10-aws-redis-instance.md
docs/user/resources/04-40-20-gcp-redis-instance.md
docs/user/resources/04-50-10-aws-redis-cluster.md
docs/user/resources/04-50-20-gcp-redis-cluster.md

docs(AwsRedis,GcpRedis): add in-transit encryption and persistence info

---

docs/user/00-30-vpc-peering.md
docs/user/00-31-vpc-peering-authorization.md
docs/user/resources/README.md
docs/user/tutorials/README.md

- Azure VPC peering is supported for all customers

docs(VpcPeering): remove SAP-internal feature label
