components/kcp/pkg/provider/gcp/client/gcpConstants.go
components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go

**Adding more APIs to gcp compute and serviceNetworking client**
- adding DeleteIpRange and GetIpRange to gcp ComputeClient for ipRange
- adding DeleteServiceConnection and PatchServiceConnection to gcp ServiceNetworkingClient for ipRange

Adding more APIs to gcp ipranges clients

---

components/kcp/cmd/main.go
components/kcp/internal/controller/cloud-resources/cloudresources_controller.go
components/kcp/pkg/common/actions/focal/fixInvalidScopeRef.go
components/kcp/pkg/provider/gcp/iprange/client/computeClient.go
components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
components/kcp/pkg/provider/gcp/iprange/loadAddress.go
components/kcp/pkg/skr/cache/cache.go
components/kcp/pkg/skr/looper/runner.go
components/kcp/pkg/skr/looper/skrLooper.go
components/kcp/pkg/skr/manager/factory.go
components/kcp/pkg/skr/manager/manager.go
components/kcp/pkg/skr/registry/builder.go
components/kcp/pkg/skr/registry/options.go
components/kcp/pkg/skr/registry/registry.go
components/kcp/pkg/skr/source/source.go
components/kcp/pkg/util/scheme.go
components/kcp/tools/dev/kind/.gitignore
components/kcp/tools/dev/kind/create-skr.sh
components/kcp/tools/dev/kind/kind-skr-config.yaml

- `SkrCache` the controller-runtime cache.Cache implementation w/out Informers, just with Indexers
- `SkrRunner` bootstraps and runs controller-runtime Controllers with `SkrManager` and controller definitions from `SkrRegistry`
- `SkrLooper` holds list of SKRs with activated CloudResources module and runs `SkrRunner` trough them
- `SkrManager` the controller-runtime manager.Manager implementation used to run Controllers
- `SkrRegistry` used to register Reconcilers we write and define their watches
- `SkrSource` the controller-runtime source.Source implementation that's not using Watch but only List() API methods
Referent implementation and usage example provided on the `CloudResourcesReconciler`
SKR handling is in this initial …

SKR looper and controller manager

---

components/kcp/pkg/skr/looper/runner.go
components/kcp/pkg/skr/registry/registry.go
components/kcp/pkg/skr/source/source.go

- added `SkrRunner.queueMonitor()` routine that will cancel Manager when all started source's queues are empty

skr manager stop on empty queue

---

components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
components/kcp/pkg/provider/gcp/iprange/syncAddress.go
components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
components/kcp/pkg/provider/gcp/iprange/updateState.go

Fixed the following:
- Adding/deleting more than one IPRange objects.
-  GCP IP Range reconciliation loop getting stopped in the middle.
NA

Fix - Adding more IPRanges and reconcilation

---

components/kcp/pkg/provider/gcp/client/provider.go
components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
components/kcp/pkg/provider/gcp/iprange/state.go
components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
components/kcp/pkg/provider/gcp/nfsinstance/client/filestoreClient.go

**FileStore Patch**
- adding patch API to FilestoreClient
- getting the project number from cloud resource manager
- fixing the issue that delete network services connection doesn't work with project id and instead needs a project number

Adding patch API to FilestoreClient and some small fixes

---

.github/workflows/pr-checks.yml
components/lib/composed/action_test.go

- Grouped run commands per module
- Added test run for KCP module
- Added build and test step for LIB module
- Fixed LIB tests

adding lib tests

---

components/kcp/api/cloud-control/v1beta1/iprange_types.go
components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
components/kcp/config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
components/kcp/pkg/provider/gcp/client/gcpConstants.go
components/kcp/pkg/provider/gcp/iprange/checkGcpOperation.go
components/kcp/pkg/provider/gcp/iprange/client/serviceNetworkingClient.go
components/kcp/pkg/provider/gcp/iprange/new.go
components/kcp/pkg/provider/gcp/iprange/syncAddress.go
components/kcp/pkg/provider/gcp/iprange/syncPsaConnection.go
components/kcp/pkg/provider/gcp/nfsinstance/checkGcpOperation.go
components/kcp/pkg/provider/gcp/nfsinstance/checkUpdateMask.go
components/kcp/pkg/provider/gcp/nfsinstance/loadNfsInstance.go
components/kcp/pkg/provider/gcp/nfsinstance/new.go
components/kcp/pkg/provider/gcp/nfsinstance/state.go
components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go

- Added time delay before calling GCP operations.
- Added functionality to check for GCP operation status before invoking the actual operations.
- Implemented NFS Patch functionality.
NA

GCP NFS Instance Reconcilation

---

components/kcp/api/cloud-control/v1beta1/conditions.go
components/kcp/api/cloud-control/v1beta1/nfsinstance_gcp_types.go
components/kcp/pkg/provider/gcp/client/gcpConstants.go
components/kcp/pkg/provider/gcp/nfsinstance/new.go
components/kcp/pkg/provider/gcp/nfsinstance/state.go
components/kcp/pkg/provider/gcp/nfsinstance/syncNfsInstance.go
components/kcp/pkg/provider/gcp/nfsinstance/validateAlways.go
components/kcp/pkg/provider/gcp/nfsinstance/validatePostCreate.go
components/kcp/pkg/provider/gcp/nfsinstance/validations.go

Added Nfs Validations for GCP
NA

GCP NFS Validations

---

components/kcp/api/cloud-control/v1beta1/nfsinstance_gcp_types.go
components/kcp/api/cloud-control/v1beta1/nfsinstance_types.go
components/kcp/config/crd/bases/cloud-control.kyma-project.io_nfsinstances.yaml
components/kcp/pkg/provider/gcp/iprange/compareStates.go
components/kcp/pkg/provider/gcp/iprange/loadAddress.go
components/kcp/pkg/provider/gcp/iprange/state.go
components/kcp/pkg/provider/gcp/iprange/syncAddress.go
components/kcp/pkg/provider/gcp/nfsinstance/state.go
components/kcp/pkg/provider/gcp/nfsinstance/validateAlways.go
components/kcp/pkg/provider/gcp/nfsinstance/validatePostCreate.go
components/kcp/pkg/provider/gcp/nfsinstance/validations.go

Updated GCP NfsInstance Validations.
Used IpRangeName instead of CIDR while creating NfsInstance
NA

GCP NfsInstance Validations

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
internal/controller/cloud-resources/gcpnfsvolume_controller.go
pkg/skr/nfs/crgcpnfsvolume/loadKcpNfsInstance.go
pkg/skr/nfs/crgcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/nfs/crgcpnfsvolume/reconciler.go
pkg/skr/nfs/crgcpnfsvolume/updateStatus.go
pkg/skr/nfs/crgcpnfsvolume/validateSpec.go

**Implementing non-PV actions for GcpNfsVolume**
- Implementing spec validation
- Implementing all other actions excluding the PV related actions
https://jira.tools.sap/browse/PHX-38

Implementing non-PV actions for GcpNfsVolume

---

.github/workflows/pr-checks.yml

- Updates GitHub actions to remove Node.js 16 deprecation warning.

Updates github actions to remove Node.js 16 deprecation warning.

---

internal/controller/cloud-control/nfsinstance_gcp_test.go
pkg/kcp/provider/gcp/mock/nfsStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/testinfra/dsl/nfsInstance.go

- adding negative automated test for gcp nfs instance
- enhancing mocks to return specified errors to simulate Filestore API errors
- Refactoring KCP GCP NfsInstance tests into limited It() to obtain better log in case of an error
https://jira.tools.sap/browse/PHX-47

Adding negative automated test to gcp nfs instance

---

pkg/skr/gcpnfsvolume/deleteKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume_test.go
pkg/skr/gcpnfsvolume/loadKcpIpRange_test.go
pkg/skr/gcpnfsvolume/loadPersistenceVolume_test.go
pkg/skr/gcpnfsvolume/state_test.go

GcpNfsVolume Reconciler Unit Tests for
- Delete KCP NfsInstance
- Delete PV
- Load KCP IPRange
- Load KCP NfsInstance
- Load PV
https://jira.tools.sap/projects/PHX/issues/PHX-52

GcpNfsVolume Reconciler Unit Tests

---

api/cloud-resources/v1beta1/condition.go
api/cloud-resources/v1beta1/labels.go
internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
internal/controller/cloud-resources/suite_test.go
pkg/composed/errors.go
pkg/composed/updateStatus.go
pkg/skr/awsnfsvolume/createVolume.go
pkg/skr/awsnfsvolume/deletePv.go
pkg/skr/awsnfsvolume/reconciler.go
pkg/skr/awsnfsvolume/requeueWaitKcpStatus.go
pkg/skr/awsnfsvolume/updateStatus.go
pkg/skr/awsnfsvolume/waitPvDeleted.go
pkg/testinfra/dsl/awsNfsVolume.go
pkg/testinfra/dsl/loadAndCheck.go
pkg/testinfra/dsl/objActions.go
pkg/testinfra/pvController.go
pkg/testinfra/run.go

- AwsNfsVolume deprovisioning
- PvController to handle Pending phase stuck for unmountable NFS servers in tests
- Modified `testinfra/dsl/IsDeleted()` to return `error` instead of `bool` and improved it to add default namespace and support ObjActions
- Added `composed/UpdateStatusBuilder.SuccessErrorNil()` to cover the case when it has to return `nil` instead of default `StopAndForget` 
- Added kubeconfig save to `./bin/cloud-manager/config` in `testinfra.Start()` so we can block it at a breakpoint and do `KUBECONFIG=./bin/cloud-manager/config/kubeconfig-[kcp|skr|garden] kubectl something` to inspect the envtest cluster resources
Not yet done, but doing a sync due to a lot of changes and added pv-controller for tests.
**Related …

AwsNfsVolume deprovisioning

---

cmd/main.go
pkg/kcp/nfsinstance/state.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/kcp/provider/gcp/nfsinstance/state_test.go
pkg/kcp/provider/gcp/nfsinstance/validateAlways_test.go

- state_test which initializes state with fake kcp k8s and fake gcp http server
- unit test for validateAlways action
https://jira.tools.sap/browse/PHX-55

gcp nfsInstance unit test for validateAlways

---

pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation_test.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance_test.go
pkg/kcp/provider/gcp/nfsinstance/state_test.go
pkg/kcp/provider/gcp/nfsinstance/validateAlways_test.go

- updating state_test so fake http server can be injected for each test
- unit test for CheckGcpOperation action
- unit test for LoadNfsInstance action
https://jira.tools.sap/browse/PHX-55

gcp nfsInstance unit test for checkGcpOperation and loadNfsInstance actions

---

pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation_test.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance_test.go
pkg/kcp/provider/gcp/nfsinstance/state_test.go
pkg/kcp/provider/gcp/nfsinstance/validateAlways_test.go
pkg/kcp/provider/gcp/nfsinstance/validatePostCreate_test.go
pkg/kcp/provider/gcp/nfsinstance/validations_test.go

- updating state_test so updateStatus works with fake k8s client
- unit test for validatePostCreate
- unit test for validations.go methods
https://jira.tools.sap/browse/PHX-55

gcp nfsInstance unit test for validatePostCreate and validations

---

pkg/kcp/provider/gcp/client/provider.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation_test.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
pkg/kcp/provider/gcp/iprange/compareStates_test.go
pkg/kcp/provider/gcp/iprange/loadAddress_test.go
pkg/kcp/provider/gcp/iprange/loadPsaConnection_test.go
pkg/kcp/provider/gcp/iprange/state_test.go
pkg/kcp/provider/gcp/iprange/syncAddress_test.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
pkg/kcp/provider/gcp/iprange/updateState_test.go

Gcp IpRange Reconciler unit tests for 
- CheckGcpOperation
- CompareStates
- LoadAddress
- LoadPsaConnection
- SyncAddress
- SyncPsaConnection
- UpdateState
https://jira.tools.sap/browse/PHX-56

Gcp IpRange Reconciler unit tests

---

pkg/composed/state.go
pkg/kcp/provider/gcp/iprange/state_test.go
pkg/kcp/provider/gcp/nfsinstance/state_test.go
pkg/kcp/scope/createGardenerClient.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/testinfra/run.go

- changed get Gardener secret to use API Reader and not the caching client as so far to avoid necessary list/watch permissions on secerets
- added `ApiReader() client.Reader` to `composed.State`

use api reader to get secrets

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
api/cloud-resources/v1beta1/iprange_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumes.yaml
config/crd/bases/cloud-resources.kyma-project.io_ipranges.yaml
config/manager/kustomization.yaml

- adding "READY" and "ERROR" column to "kubectl get" result of cloud-resources gcpNfsVolume
- adding "READY" and "ERROR" column to "kubectl get" result of cloud-resources ipRange
For the details please visit: https://jira.tools.sap/browse/PHX-59
https://jira.tools.sap/browse/PHX-59
https://jira.tools.sap/browse/PHX-60

ipRange and gcpNfsVolume to show Ready/Error status on kubectl get

---

api/cloud-resources/v1beta1/awsnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml

Description
adding "READY" and "ERROR" column to "kubectl get" result of cloud-resources awsNfsVolume
For the details please visit: https://jira.tools.sap/browse/PHX-59
Related issue(s)
https://jira.tools.sap/browse/PHX-61

awsnfsvolume to show Ready/Error status on kubectl get

---

internal/controller/cloud-resources/awsnfsvolume_test.go
pkg/skr/awsnfsvolume/createVolume.go
pkg/skr/awsnfsvolume/loadVolume.go

- removed PV owner reference creation
- change PV name to be AwsNfsVolume.status.id

chore: AWS NfsVolume remove owner reference and change name to status.id

---

sec-scanners-config.yaml

- Adds rc-tag to security scans config

fix: rc-tag is missing from security scans config

---

pkg/kcp/provider/aws/client/provider.go
pkg/kcp/provider/aws/iprange/client/client.go
pkg/kcp/provider/aws/nfsinstance/client/client.go
pkg/kcp/scope/client/awsStsClient.go

- fixes aws cached client - single cached instance can not be used due to different assumed roles and regions, so each reconcile loop must instantiate it's own

fix: aws cached client

---

pkg/kcp/provider/aws/nfsinstance/new.go
pkg/kcp/provider/aws/nfsinstance/waitMountTargetsAvailable.go

- wait for efs mount targets to become available before setting ready condition

feat(AwsNfsVolume): wait for efs mount targets availability

---

pkg/skr/cloudresources/deleteCrds.go

- do not delete cloudresources.cloud-resources.kyma-project.io crd since LifecycleManager will do it

fix: let LM delete cloudresources CRD

---

cmd/main.go
config/manager/kustomization.yaml
internal/controller/cloud-control/iprange_controller.go
internal/controller/cloud-control/nfsinstance_controller.go
internal/controller/cloud-control/suite_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/kcp/provider/gcp/client/gcpConstants.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation.go
pkg/kcp/provider/gcp/iprange/checkGcpOperation_test.go
pkg/kcp/provider/gcp/iprange/state.go
pkg/kcp/provider/gcp/iprange/state_test.go
pkg/kcp/provider/gcp/iprange/syncAddress.go
pkg/kcp/provider/gcp/iprange/syncAddress_test.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection.go
pkg/kcp/provider/gcp/iprange/syncPsaConnection_test.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation_test.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/state.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go

- Configurable reconciliation delays for GCP access
- Separate delays for actual GCP calls and testing.
https://jira.tools.sap/browse/PHX-87

fix: Separate timer values for test and actual GCP provider calls

---

api/cloud-control/v1beta1/vpcpeering_types.go
internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/mock/type.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/updateSuccessStatus.go
pkg/kcp/vpcpeering/reconciler.go

- Use vpc peering connection id returned by the mock instead of using hard coded value

feat: KCP AWS VpcPeering mock

---

api/cloud-resources/v1beta1/awsnfsvolume_types.go
api/cloud-resources/v1beta1/iprange_ref.go
internal/controller/cloud-resources/iprange_controller.go
pkg/skr/gcpnfsvolume/validateSpec.go
pkg/skr/iprange/preventDeleteOnGcpNfsVolumeUsage.go
pkg/skr/iprange/reconciler.go
pkg/skr/iprange/state.go

Verify no GcpNfsVolume has a ref to IpRange while deleting IpRange
- Fixing preventDeleteOnAwsNfsVolumeUsage to skip if not an aws skr
- Adding preventDeleteOnGcpNfsVolumeUsage
- Making sure gcpNfsVolume validation doesn't run for deletion scenario. If not check, this can block deletion of gcpNfsVolume if ipRange is in warning state
https://jira.tools.sap/browse/PHX-104

fix: verify no gcpNfsVolume has a ref to ipRange while deleting

---

pkg/kcp/provider/gcp/mock/nfsRestoreStore.go
pkg/kcp/provider/gcp/mock/server.go
pkg/skr/gcpnfsvolumebackup/loadScope.go
pkg/skr/gcpnfsvolumerestore/addFinalizer_test.go
pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
pkg/skr/gcpnfsvolumerestore/checkRestoreOperation_test.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup_test.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume_test.go
pkg/skr/gcpnfsvolumerestore/loadScope_test.go
pkg/skr/gcpnfsvolumerestore/removeFinalizer_test.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
pkg/skr/gcpnfsvolumerestore/state_test.go

- Adding unit tests for GcpNfsVolumeRestore reconciler actions
https://jira.tools.sap/browse/PHX-113

feat: GcpNfsVolumeRestore unit tests

---

pkg/skr/gcpnfsvolume/state_test.go
pkg/skr/gcpnfsvolume/validateSpec.go

- gcpNfsVolume to reference iprange with correct namespace
- updating unit test to test an iprange in a different namespace
https://jira.tools.sap/browse/PHX-117

fix: gcpNfsVolume to reference iprange with correct namespace

---

pkg/skr/gcpnfsvolumebackup/addFinalizer_test.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume_test.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/loadScope.go
pkg/skr/gcpnfsvolumebackup/loadScope_test.go
pkg/skr/gcpnfsvolumebackup/removeFinalizer_test.go
pkg/skr/gcpnfsvolumebackup/state_test.go
pkg/skr/gcpnfsvolumebackup/updateStatus.go
pkg/skr/gcpnfsvolumebackup/updateStatus_test.go

Added unit tests for the following GcpNfsVolumeBackup actions
- addFinalizer
- createNfsBackup
- deleteNfsBackup
- loadGcpNfsVolume
- loadNfsBackup
- loadScope
- removeFinalizer
- updateStatus
https://jira.tools.sap/browse/PHX-121

test: GcpNfsVolumeBackup unit tests

---

pkg/kcp/provider/aws/iprange/client/client.go
pkg/kcp/provider/aws/iprange/new.go
pkg/kcp/provider/aws/iprange/state.go
pkg/kcp/provider/aws/iprange/v1/addFinalizer.go
pkg/kcp/provider/aws/iprange/v1/checkCidrBlockStatus.go
pkg/kcp/provider/aws/iprange/v1/checkCidrOverlap.go
pkg/kcp/provider/aws/iprange/v1/checkSubnetOverlap.go
pkg/kcp/provider/aws/iprange/v1/createSubnets.go
pkg/kcp/provider/aws/iprange/v1/deleteSubnets.go
pkg/kcp/provider/aws/iprange/v1/disassociateVpcAddressSpace.go
pkg/kcp/provider/aws/iprange/v1/ensureShootZonesAndRangeSubnetsMatch.go
pkg/kcp/provider/aws/iprange/v1/extendVpcAddressSpace.go
pkg/kcp/provider/aws/iprange/v1/findCloudResourceSubnets.go
pkg/kcp/provider/aws/iprange/v1/loadSubnets.go
pkg/kcp/provider/aws/iprange/v1/loadVpc.go
pkg/kcp/provider/aws/iprange/v1/new.go
pkg/kcp/provider/aws/iprange/v1/preventCidrEdit.go
pkg/kcp/provider/aws/iprange/v1/removeFinalizer.go
pkg/kcp/provider/aws/iprange/v1/removeReadyCondition.go
pkg/kcp/provider/aws/iprange/v1/splitRangeByZones.go
pkg/kcp/provider/aws/iprange/v1/state.go
pkg/kcp/provider/aws/iprange/v1/updateSuccessStatus.go
pkg/kcp/provider/aws/iprange/v1/util.go
pkg/kcp/provider/aws/iprange/v1/waitCidrBlockDisassociated.go
pkg/kcp/provider/aws/iprange/v1/waitSubnetsDeleted.go
pkg/kcp/provider/aws/mock/vpcStore.go

Simple refactoring and move of `pkg/kcp/provider/aws/iprange` into `pkg/kcp/provider/aws/iprange/v1` to make room for `pkg/kcp/provider/aws/iprange/v2` implementation
- moved `pkg/kcp/provider/aws/iprange` to `pkg/kcp/provider/aws/iprange/v1`
- added general `StateFactory` and `New()` constructor in `pkg/kcp/provider/aws/iprange` that simply delegates to old v1 implementation, so that external usage remains the same
- added `DescribeVpc()` to iprange aws client, not used yet

chore(KCP IpRange): preps for KCP IpRange impl v2 and optional cidr

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/mock/vpcPeeringStore.go
pkg/kcp/provider/azure/util/resources_test.go
pkg/kcp/provider/azure/vpcpeering/client/client.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go

- Azure peering name should be the same as the name of the applied resource in KCP

feat(AzureVpcPeering): KCP Create VpcPeering change peering name

---

api/cloud-control/v1beta1/vpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
go.mod
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/config/config.go
pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/mock/server.go
pkg/kcp/provider/azure/mock/vpcPeeringStore.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeeringRemote.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/state.go
pkg/testinfra/dsl/scope.go

- added remoteId which identifies remote vpc peering connection
- subscriptionId and tenantId has been removed from config as they will be read from scope (for KCP) or specified in VpcPeering (SKR)

feat(AzureVpcPeering): KCP Load vpc peerings

---

api/cloud-resources/v1beta1/awsnfsvolume_types.go
config/crd/bases/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
config/dist/skr/crd/bases/providers/aws/cloud-resources.kyma-project.io_awsnfsvolumes.yaml
internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/suite_test.go
pkg/skr/awsnfsvolume/reconciler.go
pkg/skr/awsnfsvolume/state.go
pkg/skr/common/defaultiprange/checkIfIpRangeIsSpecified.go
pkg/skr/common/defaultiprange/createDefaultSkrIpRange.go
pkg/skr/common/defaultiprange/findDefaultSkrIpRange.go
pkg/skr/common/defaultiprange/loadSpecifiedIpRange.go
pkg/skr/common/defaultiprange/new.go
pkg/skr/common/defaultiprange/state.go
pkg/skr/common/defaultiprange/waitIpRangeReady.go
pkg/testinfra/dsl/awsNfsVolume.go

- set `spec.iprangeref` as optional in AwsNfsVolume
- added `skr/common/defaultiprange` package that implements the feature 
- modified `AwsNfsVolume` flow to use new `defaultiprange` package
- modified `testinfra/dsl/CreateAwsNfsVolume` not to force `spec.iprangeref`
- added test scenarios for empty iprangeref

feat(AwsNfsVolume): optional iprange

---

internal/controller/cloud-resources/awsnfsvolume_test.go
pkg/skr/awsnfsvolume/createPersistentVolumeClaim.go
pkg/skr/awsnfsvolume/createVolume.go
pkg/skr/awsnfsvolume/reconciler.go
pkg/skr/awsnfsvolume/removePersistenceVolumeClaimFinalizer.go
pkg/skr/awsnfsvolume/removePersistenceVolumeFinalizer.go

- Adds finalizer to PV that is created for AwsNfsVolume
- Adds mechanism to remove said PV finalizer when AwsNfsVolume is beign deleted
- Adds finalizer to PVC that is created for AwsNfsVolume
- Adds mechanism to remove said PVC finalizer when AwsNfsVolume is beign deleted

feat(AwsNfsVolume): add finalizer to PV and PVC

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
pkg/skr/gcpnfsvolume/loadPersistentVolumeClaim.go
pkg/skr/gcpnfsvolume/validatePVC.go
pkg/skr/gcpnfsvolume/validatePVC_test.go

- fixes existing validatePVC
- removes validation from loadPVC

refactor(GcpNfsVolume): move validation from loadPVC to validatePVC

---

pkg/skr/awsnfsvolume/createPersistentVolumeClaim.go
pkg/skr/awsnfsvolume/createVolume.go
pkg/skr/awsnfsvolume/reconciler.go
pkg/skr/awsnfsvolume/util.go
pkg/skr/awsnfsvolume/validatePersistentVolume.go
pkg/skr/awsnfsvolume/validatePersistentVolumeClaim.go
pkg/skr/awsnfsvolume/validatePersistentVolumeClaim_test.go
pkg/skr/awsnfsvolume/validatePersistentVolume_test.go

- validate that if PersistentVolume and PersistentVolumeCLaim exixst, those belongs to us, by checking the values of labels - LabelNfsVolName, LabelNfsVolNS

feat(AwsNfsVolume): validate PersistentVolume and PersistentVolumeClaim

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/mock/storeSubscriptionContext.go
pkg/kcp/provider/azure/vpcpeering/client/client.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/removeFinalizer.go
pkg/kcp/provider/azure/vpcpeering/removeReadyCondition.go
pkg/skr/azurevpcpeering/deleteKcpVpcPeering.go
pkg/skr/azurevpcpeering/loadKcpAzureVpcPeering.go
pkg/skr/azurevpcpeering/reconciler.go
pkg/skr/azurevpcpeering/removeFinalizer.go
pkg/skr/azurevpcpeering/updateStatus.go

- Deletes VirtualNetworkPeering from SKR subscription when VpcPeering on KCP is deleted.
- Deletes KCP VpcPeering when SKR AzureVpcPeering is deleted
- Shows friendly error to user instead of provider API error

feat (AzureVpcPeering): Handles object deletion

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/gcpredisinstance_types.go
config/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/crd/bases/cloud-resources.kyma-project.io_gcpredisinstances.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_redisinstances.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpredisinstances.yaml
pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/skr/gcpredisinstance/createKcpRedisInstance.go
pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go

- allow user to define if auth is enabled `.spec.authEnabled`
- allow user to define transit encryption mode `.spec.transitEncryptionMode`
- show `Deleting` state while GcpRedisInstance is being deleted

feat(GcpRedisInstance): add auth settings to API

---

Makefile

- Upgrading k8s in tests due to planned K8s Upgrade (from v.1.28 to v.1.29) in managed kyma runtime
- ...
- ...
https://github.tools.sap/kyma/backlog/issues/5460

chore: Test with k8s v1.29.3

---

internal/controller/cloud-control/iprange_aws_test.go
internal/controller/cloud-control/iprange_gcp_test.go
pkg/common/actions/focal/loadScopeFromRef.go
pkg/testinfra/dsl/awsIpRange.go
pkg/testinfra/dsl/kcpIpRange.go
tools/scripts/kcp/listSkrs.mjs
tools/scripts/taskrun/moduleDisable.mjs

- added taskrun script moduleDisable

chore: added taskrun script moduleDisable

---

api/cloud-control/v1beta1/redisinstance_types.go
api/cloud-resources/v1beta1/gcpredisinstance_types.go
internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/gcpredisinstance_test.go
internal/controller/cloud-resources/iprange_test.go
internal/controller/cloud-resources/suite_test.go
pkg/testinfra/dsl/awsNfsVolume.go
pkg/testinfra/dsl/commonIpRange.go
pkg/testinfra/dsl/gcpRedisInstance.go
pkg/testinfra/dsl/loadAndCheck.go
pkg/testinfra/dsl/redisInstance.go

- add SKR GcpRedisInstance scenario tests
- Scenario: SKR GcpRedisInstance is created with specified IpRange
- Scenario: SKR GcpRedisInstance is deleted
- Scenario: SKR GcpRedisInstance is created with empty IpRange when default IpRange does not exist
- Scenario: SKR GcpRedisInstance is created with empty IpRangeRef when default IpRange already exist
- Scenario: SKR GcpRedisInstance IpRangeRef is required when ff IpRangeAutomaticCidrAllocation is disabled
- add common `WithIpRange` `ObjAction`

test(GcpRedisInstance): add scenario tests

---

internal/controller/cloud-resources/awsnfsvolume_test.go
internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/skr/awsnfsvolume/util.go
pkg/skr/awsnfsvolume/validatePersistentVolume_test.go
pkg/skr/gcpnfsvolume/createPersistenceVolume_test.go
pkg/skr/gcpnfsvolume/updateId.go
pkg/skr/gcpnfsvolume/util.go
pkg/skr/gcpnfsvolume/validatePV_test.go

- default PV name is changed from` (GcpNfsVolume|AwsNfsVolume).metadata.name` to `(GcpNfsVolume|AwsNfsVolume).status.id`

feat(GcpNfsVolume, AwsNfsVolume): change default PV name

---

pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance_test.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance_test.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/setProcessing.go
pkg/skr/gcpnfsvolume/setProcessing_test.go

- Fixed the GCP NFS Instance to be created with name `cm-<kcp-nfs-instance-name>` instead of the GcpNfsVolume name to avoid name collisions
- Fixed the GcpNfsVolume.Status.State was empty for long time when the long running IpRange creation is in progress.
https://jira.tools.sap/browse/PHX-178
https://jira.tools.sap/browse/PHX-179

fix(GcpNfsVolume) : Fix for GCP NfsInstance naming.

---

internal/controller/cloud-control/nfsinstance_aws_test.go
internal/controller/cloud-control/nfsinstance_gcp_test.go
internal/controller/cloud-control/redisinstance_gcp_test.go
internal/controller/cloud-control/suite_test.go
pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/redisinstance/new.go
pkg/kcp/provider/gcp/redisinstance/updateStatus.go
pkg/kcp/provider/gcp/redisinstance/updateStatusId.go
pkg/skr/gcpredisinstance/deleteKcpRedisInstance.go
pkg/testinfra/dsl/commonAssertions.go
pkg/testinfra/dsl/commonIpRange.go
pkg/testinfra/dsl/nfsInstance.go
pkg/testinfra/dsl/redisInstance.go

- add scenario test for KCP RedisInstance
- move `.status.id` update in KCP RedisInstance reconciler from `updateStatus` action to `updateStatusId` action that happens before GCP MemoryStore Redis instance is ready
- use common newly intorduced `WithIpRange` `ObjAction` in NfsInstance test

test(RedisInstance): add scenario tests

---

README.md
pkg/feature/log.go
pkg/feature/testdata/apiDisabled.yaml
pkg/skr/runtime/looper/runner.go

chore: feature logs landscape

---

pkg/kcp/provider/gcp/mock/memoryStoreClientFake.go
pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/client/util.go
pkg/skr/gcpredisinstance/updateId.go

- redis instance id in gcp memorystore is prefixed with `cm-` instead of `r-`

feat(GcpRedisInstance): swap gcp redis instance name prefix to 'cm'

---

api/cloud-resources/v1beta1/nfsbackupschedule_types.go
pkg/feature/context.go
pkg/feature/object2feature.go
pkg/feature/object2feature_test.go
pkg/feature/objectKinds.go
pkg/feature/objectKinds_test.go
pkg/feature/types/types.go

- added universal `ObjectKinds()` to find obj, crd and busola kind - extracted from `ContextBuilder.KindsFromObject()`
- modified `ContextBuilder.KindsFromObject()` to use new `ObjectKinds()`
- added in `ObjectToFeature()` feature  extraction from unstructured crd and busola cm and switched kinds detection to added `ObjectKinds()`
- added unit tests for feature detection on unstrctured crd and busola cm
- added unit tests to check if all cloud-resources resources implement `FeatureAwareObject` and `ProviderAwareObject`
- removed deprecated `objectToFeaturePredetermined()` that was detecting feature based on hard coded maps

chore: feature from unstructured crd and busola cm

---

pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/createSubnetGroup.go
pkg/kcp/provider/aws/redisinstance/loadElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/loadSubnetGroup.go
pkg/kcp/provider/aws/redisinstance/util.go
pkg/skr/awsredisinstance/waitKcpRedisInstanceDeleted.go
pkg/skr/gcpredisinstance/loadKcpRedisInstance.go
pkg/skr/gcpredisinstance/reconciler.go
pkg/skr/gcpredisinstance/waitKcpRedisInstanceDeleted.go

- Prefix AwsRedisInstance cloud provider resources with `cm-` to be compliant with their name requirement
- Refactor some logs

fix(AwsRedisInstance): prefix resources with '-cm'

---

api/cloud-control/v1beta1/iprange_types.go
config/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_ipranges.yaml
pkg/kcp/provider/gcp/iprange/v2/compareStates.go
pkg/kcp/provider/gcp/iprange/v2/compareStates_test.go
pkg/kcp/provider/gcp/iprange/v2/loadAddress.go
pkg/kcp/provider/gcp/iprange/v2/loadAddress_test.go
pkg/kcp/provider/gcp/iprange/v2/new.go
pkg/kcp/provider/gcp/iprange/v2/state.go
pkg/kcp/provider/gcp/iprange/v2/state_test.go
pkg/kcp/provider/gcp/iprange/v2/syncAddress.go
pkg/kcp/provider/gcp/iprange/v2/syncAddress_test.go
pkg/kcp/provider/gcp/iprange/v2/updateStatusId.go
pkg/kcp/provider/gcp/iprange/v2/util.go
pkg/kcp/provider/gcp/iprange/v2/validateCidr.go
pkg/kcp/provider/gcp/meta/metadata.go
pkg/kcp/provider/gcp/nfsinstance/state.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go

- IpRange that is allocated in GCP is now named by using KCP IpRange resource name (with `cm-` prefix)
- Handle backwards compatibility to still be able to load old name
- When delete range operation is called, name from loaded address is used
Within one GCP project, two different VPC Networks can not have IpRange with same name. This PR should solve the potential conflicts that can occur due to that fact.
Fixes https://github.com/kyma-project/cloud-manager/issues/372

fix(IpRange): change GCP IpRange naming strategy

---

api/cloud-resources/v1beta1/labels.go
internal/controller/cloud-resources/awsredisinstance_test.go
internal/controller/cloud-resources/gcpredisinstance_test.go
pkg/skr/awsredisinstance/deleteAuthSecret.go
pkg/skr/awsredisinstance/loadAuthSecret.go
pkg/skr/awsredisinstance/util.go
pkg/skr/gcpredisinstance/deleteAuthSecret.go
pkg/skr/gcpredisinstance/loadAuthSecret.go
pkg/skr/gcpredisinstance/util.go

- Labels cant hold more than 63 characters, while .metadata.name can be 255. Thats why .status.id is used
- This is a breaking change that is not backwards compatible (but its ok, because redis resource is not GA yet)

refactor(GcpRedisInstance, AwsRedisInstance): track secret ownership via parent .status.id label

---

config/featureToggles/featureToggles.yaml
internal/controller/cloud-resources/gcpnfsvolume_test.go
pkg/skr/gcpnfsvolume/loadScope_test.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/testinfra/dsl.go
pkg/testinfra/dsl/gcpNfsVolume.go

- new unit tests for GcpNfsVolume actions
- new scenarios in GcpNfsVolume reconciler tests
- ...
Resolves #402

test: GcpNfsVolume optional location tests

---

api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/patchAfterMakeManifests.sh

- MaxLength & Pattern Validations moved to XValidation rules

feat (AzureVpcPeering): adds XValidation rules to RemotePeeringName

---

pkg/kcp/provider/gcp/mock/vpcPeeringStore.go
pkg/kcp/provider/gcp/vpcpeering/client/vpcPeeringClient.go
pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
pkg/kcp/provider/gcp/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/gcp/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/gcp/vpcpeering/loadKymaVpcPeering.go
pkg/kcp/provider/gcp/vpcpeering/state.go

- The peering name on the kyma project now has the prefix cm- to identify as a cloud manager resource
- The peering name on the kyma project now has the metadata.name of the CRD as a suffix

feat(GCPVpcPeering) Changing the kyma network peering to be cm-{metadata.name}

---

api/cloud-resources/v1beta1/gcpvpcpeering_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpvpcpeerings.yaml
pkg/kcp/provider/gcp/vpcpeering/client/vpcPeeringClient.go
pkg/kcp/provider/gcp/vpcpeering/createKymaVpcPeering.go
pkg/kcp/provider/gcp/vpcpeering/state.go
pkg/skr/gcpvpcpeering/createKcpVpcPeering.go
pkg/skr/gcpvpcpeering/loadKcpGcpVpcPeering.go

- Using the short shootName on the peering challenge i.e: abc1234.
- Using another environment variable which will be used to store the auth details of the service account that will execute the peering operations and it won't be the same used by cloud-manager.

feat(GCPVpcPeering) Short shootName on peering challenge

---

api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/state_test.go
pkg/skr/gcpnfsvolumerestore/addFinalizer.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
pkg/skr/gcpnfsvolumerestore/state_test.go

- Change the naming of backup in the backend (Gcp Filestore Backup) to cm-<uuid>
- Making sure that GcpNfsVolume, GcpNfsVolumeBackup and GcpNfsVolumeRestore can be deleted independently
- Updating unit tests
Resolves #462

fix(GcpNfsVolumeBackup): Fix for GCP Filestore backup naming

---

api/cloud-resources/v1beta1/gcpnfsvolume_types.go
pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/validateSpec.go
pkg/skr/gcpnfsvolume/validateSpec_test.go

- Preventing legacy filestore tiers from getting created
- Fixing the nfs capacity validation to cover the capacity limitations based on increments for regional and zonal filestores
- Fixing unit tests
Resolves #464

fix(GcpNfsVolume): Fix for blocking legacy filestore tiers

---

api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsvolumebackups.yaml
config/patchAfterMakeManifests.sh
internal/controller/cloud-resources/gcpnfsvolumebackup_test.go
pkg/skr/backupschedule/backupImpl.go
pkg/skr/backupschedule/calculateOnetimeSchedule_test.go
pkg/skr/backupschedule/createBackup_test.go
pkg/skr/backupschedule/evaluateNextRun.go
pkg/skr/backupschedule/state_test.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance.go
pkg/skr/gcpnfsvolume/modifyKcpNfsInstance_test.go
pkg/skr/gcpnfsvolume/state_test.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup.go
pkg/skr/gcpnfsvolumebackup/deleteNfsBackup_test.go
pkg/skr/gcpnfsvolumebackup/loadNfsBackup.go
pkg/skr/gcpnfsvolumebackup/reconciler.go
pkg/skr/gcpnfsvolumebackup/state_test.go
pkg/skr/gcpnfsvolumebackup/validateSpec.go
pkg/skr/gcpnfsvolumebackup/validateSpec_test.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
pkg/skr/gcpnfsvolumerestore/state_test.go
pkg/skr/runtime/looper/cyclicQueue_smoke_test.go
pkg/testinfra/dsl/gcpNfsVolumeBackup.go

- Make location optional in GcpNfsVolumeBackup
- Integration/Unit tests for the change
Resolves #463

feat(GcpNfsVolumeBackup): make location optional

---

internal/controller/cloud-resources/iprange_controller.go
internal/controller/cloud-resources/iprange_test.go
pkg/skr/awsredisinstance/ignorant.go
pkg/skr/gcpredisinstance/ignorant.go
pkg/skr/iprange/preventDeleteOnAwsRedisInstanceUsage.go
pkg/skr/iprange/preventDeleteOnGcpRedisInstanceUsage.go
pkg/skr/iprange/reconciler.go

- IpRange cant be deleted if there is an existing GcpRedisInstance using it
- IpRange cant be deleted if there is an existing AwsRedisInstance using it
- Scenario tests for the above
- Out of scope, but added: Scenario test: IpRange cant be deleted if there is an existing GcpNfsInstance using it
https://github.com/kyma-project/cloud-manager/issues/543

feat(IpRange): forbid IpRange delete if RedisInstance is using it

---

config/samples/cloud-control_v1beta1_vpcpeering.yaml
config/samples/cloud-resources_v1beta1_azurevpcpeering.yaml
docs/user/resources/04-40-10-azure-vpc-peering.md
docs/user/tutorials/01-30-azure-vpc-peering.md
docs/user/tutorials/README.md

- update docs and samples after removing allowVnetAcces from AzureVpcPeering API
#526

feat(AzureVpcPeering): updates docs and samples

---

cmd/main.go
internal/controller/cloud-control/nfsinstance_gcp_test.go
pkg/common/ignorant/store.go
pkg/composed/state.go
pkg/feature/ffApiDisabled_test.go
pkg/feature/ffGcpNfsVolumeAutomaticLocationAllocation.go
pkg/feature/ffIpRangeAutomaticCidrAllocation.go
pkg/feature/init.go
pkg/testinfra/dsl/gcpNfsVolume.go

chore: feature flags logger

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go

- use util.Timing so that tests can run faster

chore(AzureVpcPeering): use util.Timing

---

pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go

- Optional value for GcpNfsVolumeBackup.Spec.Source.Volume.Namespace 
- Optional value for GcpNfsVolumRestore.Spec.Destination.Volume.Namespace 
- ...
https://github.com/kyma-project/cloud-manager/issues/585

fix(GcpNfsVolumeBackup/Restore) optional nfsvolume ref namespace

---

config/manager/kustomization.yaml
pkg/kcp/provider/gcp/client/gcpConstants.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState.go
pkg/kcp/provider/gcp/nfsinstance/checkNUpdateState_test.go
pkg/kcp/provider/gcp/nfsinstance/state.go
pkg/kcp/provider/gcp/nfsinstance/syncNfsInstance.go
pkg/skr/gcpnfsvolume/deletePersistenceVolume.go

- Change the default GCP API timeout from 3 to 8 seconds
- Change Gcp NfsInstance loop to recover when creation times out and Filestore is already created in the next loop
- unit test updates
Resolves #574

fix: GcpNfsVolume to recover from timout during creation

---

api/cloud-control/v1beta1/vpcpeering_types.go
api/cloud-resources/v1beta1/awsredisinstance_types.go
pkg/kcp/provider/azure/mock/networkStore.go
pkg/kcp/provider/azure/vpcpeering/client/client.go
pkg/kcp/provider/azure/vpcpeering/createRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/createVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadRemoteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/loadVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/waitVpcPeeringReady.go
pkg/skr/azurevpcpeering/updateStatus.go

- Azure client modified not to use PullUntilDone as it may wait indefinitely.
- KCP Azure reconciler logic is changed according to the change that client.CreatePeering no longer returns created armnetwork.VirtualNetworkPeering object
- SKR updateStatus update logic is simplified

feat(AzureVpcPeering): remove PollUntilDone

---

config/config/skrRuntime.yaml
config/dist/kcp/crd/kustomization.yaml
pkg/kcp/provider/gcp/mock/nfsRestoreStore.go
pkg/kcp/provider/gcp/nfsrestore/client/fileRestoreClient.go
pkg/skr/common/leases/lease.go
pkg/skr/common/leases/lease_test.go
pkg/skr/gcpnfsvolumerestore/acquireLease.go
pkg/skr/gcpnfsvolumerestore/acquireLease_test.go
pkg/skr/gcpnfsvolumerestore/addFinalizer_test.go
pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
pkg/skr/gcpnfsvolumerestore/findRestoreOperation_test.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go
pkg/skr/gcpnfsvolumerestore/reconciler.go
pkg/skr/gcpnfsvolumerestore/releaseLease.go
pkg/skr/gcpnfsvolumerestore/releaseLease_test.go
pkg/skr/gcpnfsvolumerestore/removeFinalizer.go
pkg/skr/gcpnfsvolumerestore/removeFinalizer_test.go
pkg/skr/gcpnfsvolumerestore/runNfsRestore_test.go
pkg/skr/gcpnfsvolumerestore/setProcessing_test.go
pkg/skr/gcpnfsvolumerestore/state_test.go
pkg/skr/runtime/config/config.go
pkg/skr/runtime/config/config_test.go

- Introducing leasing mechanism to prevent conflicting actions
- Adding api to restore client to find an existing running restore to prevent duplicate execution of restore 
Resolves #584

fix(gcpnfsvolumerestore): preventing duplicate filestore restores

---

api/cloud-resources/v1beta1/gcpnfsbackupschedule_types.go
config/crd/bases/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
config/dist/skr/crd/bases/providers/gcp/cloud-resources.kyma-project.io_gcpnfsbackupschedules.yaml
config/patchAfterMakeManifests.sh
pkg/skr/backupschedule/backupImplGcpNfs.go
pkg/skr/backupschedule/deleteCascade.go
pkg/skr/backupschedule/loadSource.go

- optional namespace in GcpNfsBackupSchedule `sourceRef`
- `DeleteCascade` option is not deleting the backup resources.
part of #585
fixes #623

fix(GcpNfsBackupSchedule): optional sourceRef namespace name

---

api/cloud-control/v1beta1/vpcpeering_types.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go

- Allows KCP Azure VpcPeering to specify local peering name. If local peering name is not specified it will failback to object name

feat(AzureVpcPeering): local peering name

---

pkg/kcp/provider/aws/vpcpeering/acceptVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/checkNetworkTag.go
pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
pkg/kcp/provider/aws/vpcpeering/createRoutes.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/deleteRoutes.go
pkg/kcp/vpcpeering/state.go
pkg/skr/awsvpcpeering/deleteKcpVpcPeering.go
pkg/skr/awsvpcpeering/reconciler.go
pkg/skr/awsvpcpeering/waitKcpVpcPeeringDeleted.go

- wait KcpVpcPeering to be deleted before deleting Network
- handle retriable errors

feat(AwsVpcPeering): wait KcpVpcPeering deleted before deleting Network

---

pkg/skr/azurevpcpeering/reconciler.go
pkg/skr/azurevpcpeering/waitKcpVpcPeeringDeleted.go

- wait VpcPeering to be deleted before deleting Network

feat(AzureVpcPeering): wait KcpVpcPeering deleted before deleting Network

---

internal/controller/cloud-control/iprange_azure_test.go
internal/controller/cloud-control/network_azure_test.go
pkg/kcp/provider/azure/iprange/securityGroupCreate.go
pkg/kcp/provider/azure/network/initState.go

Azure in tag name does not accept `<>%&\?/.`. Until use case for tags is identified and their names unified across providers removing them from Azure implementation. 
- remove tags for Azure 

fix: Azure tags removed

---

docs/user/tutorials/01-30-azure-vpc-peering.md

- Adds missing command that exports IP_ADDRESS of created Azure VM

docs(AzureVpcPeering): adds missing IP_ADDRESS export

---

pkg/kcp/iprange/kcpNetworkCreate.go
pkg/testinfra/dsl/conditions.go

- changed KCP IpRange create KCP Network not to set error condition when create network fails with already exists error

chore: tweak KCP IpRange create kcp network error handling

---

Makefile
api/cloud-control/v1beta1/scope_types.go
config/crd/bases/cloud-control.kyma-project.io_scopes.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_scopes.yaml
pkg/kcp/scope/addKymaFinalizer.go
pkg/kcp/scope/addReadyCondition.go
pkg/kcp/scope/checkGcpOperations.go
pkg/kcp/scope/enableApisGcp.go
pkg/kcp/scope/findKymaModuleState.go
pkg/kcp/scope/loadNetworks.go
pkg/kcp/scope/predicates.go
pkg/kcp/scope/reconciler.go
pkg/kcp/scope/removeKymaFinalizer.go
pkg/testinfra/run.go

- refactored the KCP Scope reconciler action flow so it's easier to read and understand
- added field `status.state` to KCP Scope
- added `CloneForPatchStatus()` to KCP Scope
- changed KCP Scope reconciler to use patch for adding and removing Kyma finalizer
- changed KCP Scope reconciler to update status with ready condition only if there's a change and to use patch then
- made KCP Scope state.kymaModuleState to default to NotPresent if Kyma does not exist (not important now since it stops before that step if Kyma not found, but will be later when we start orphan clenup)
- changed KCP Scope to be able to work in case when Kyma does not exist but Scope exists (same as above)
- renamed in `kcp/scope` predicates `ObjIsLoadedPredicate` to …

chore: KCP Scope refactoring

---

internal/controller/cloud-control/network_azure_test.go
pkg/common/network.go
pkg/kcp/iprange/kcpNetworkInit.go
pkg/kcp/network/preventCreationOfNonCmManagedNetwork.go
pkg/kcp/network/reconciler.go
pkg/kcp/provider/azure/network/initState.go
pkg/kcp/provider/azure/network/state.go
pkg/kcp/provider/azure/network/statusReady.go
pkg/kcp/provider/azure/network/vnetCreate.go
pkg/kcp/provider/azure/network/vnetDelete.go
pkg/kcp/provider/azure/network/vnetLoad.go

- changed KCP Network Azure in case of CM network to create vnet with `{shoot-vnet-name}--cm` as specified [here](https://github.com/kyma-project/cloud-manager/blob/main/tools/dev/reconcilers/azure-peering-kyma-cm.png)

fix: KCP Managed Network for Azure vnet name

---

api/cloud-control/v1beta1/vpcpeering_builder.go
api/cloud-control/v1beta1/vpcpeering_types.go
api/cloud-resources/v1beta1/azurevpcpeering_types.go
config/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/crd/bases/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
config/dist/kcp/crd/bases/cloud-control.kyma-project.io_vpcpeerings.yaml
config/dist/skr/crd/bases/providers/azure/cloud-resources.kyma-project.io_azurevpcpeerings.yaml
internal/api-tests/vpcpeering_test.go
internal/controller/cloud-control/vpcpeering_aws_test.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
pkg/skr/azurevpcpeering/createKpcVpcPeering.go

feat(AzureVpcPeering): delete remote peering

---

pkg/kcp/scope/checkGcpOperations.go
pkg/kcp/scope/enableApisGcp.go

- Handing the situation where enabling api for gcp is done right away
- Checking operation id is not "operations/noop.DONE_OPERATION" enabling apis for gcp
- retrying operation again if it is not found of invalid (404 or 400)
Fixes #678

fix(scope): hardening gcp enableApis and check operation status

---

api/cloud-control/v1beta1/scope_types.go
internal/controller/cloud-control/scope_aws_test.go
internal/controller/cloud-control/scope_azure_test.go
internal/controller/cloud-control/scope_gcp_test.go
pkg/feature/context.go
pkg/feature/context_test.go
pkg/kcp/nuke/scopeDelete.go
pkg/kcp/scope/ensureScopeCommonFields.go
pkg/kcp/scope/findShootName.go
pkg/kcp/scope/loadKyma.go
pkg/kcp/scope/predicates.go
pkg/kcp/scope/skrActivate.go
pkg/kcp/scope/skrDeactivate.go
pkg/skr/runtime/looper/skrLooper.go
pkg/testinfra/dsl/kyma.go

The Kyma CR can be deleted while Scope still exists, like when SKR cluster is deleted. Then we need to deactive that scope and SKR from the skrLooper and decease the `cloud_manager_skr_runtime_module_active_count` metrics. That metrics has labels "kymaName", "globalAccountId", "subAccountId", "shootName", "region", "brokerPlanName", where all but the first are not accessible anymore since Kyma was deleted. Hence, we need to copy those Kyma labels to Scope so that data is available at the time Scope is deleted and SKR deactivated so the proper metric can be decreased. 
- added in `scope.predicateScopeCreateOrUpdateNeeded` a check if Kyma labels are copied
- added in `scope.ensureScopeCommonFields` copying of Kyma labels
- replaced …

fix: copy Kyma labels to Scope

---

pkg/kcp/provider/aws/mock/elastiCacheClientFake.go

- multiple mutexes were unnecessary, so they are replaced by a single mutex to improve readability

test(AwsRedisInstance): refactor elastiCacheClientFake to use single mutex

---

internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/mock/routeTablesStore.go
pkg/kcp/provider/aws/mock/vpcPeeringStore.go
pkg/kcp/provider/aws/vpcpeering/client/client.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/testinfra/dsl/kcpVpcPeering.go

- Improve route table tests
- Moved inline string declaration to consts as they are being reused
- Added  DescribeVpcPeeringConnection to avoid looping every time to find connection by id
- Added helper methods GetRoute and GetRouteCount to improve test readablity

chore(AwsVpcPeering): route table tests

---

config/samples/cloud-resources_v1beta1_awsredisinstance.yaml
config/samples/cloud-resources_v1beta1_gcpredisinstance.yaml
docs/user/resources/04-60-gcp-redis-instance.md
docs/user/resources/04-70-aws-redis-instance.md
docs/user/tutorials/01-60-gcp-redis-instance.md
docs/user/tutorials/01-70-aws-redis-instance.md
pkg/feature/README.md

docs(GcpRedisInstance,AwsRedisInstance): update docs

---

api/cloud-control/v1beta1/vpcpeering_builder.go
internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go

- fixes the issue with deleing local VPC peering connection when LocalPeeringName is used.

fix(AzureVpcPeering): fixes deletion of local VPC peering

---

pkg/kcp/provider/azure/iprange/privateDnsZoneCreate.go

- Remove uneeded param in loging causing cernel panic.

fix(AzureRedis): remove odd param causing panic

---

docs/user/resources/04-40-10-azure-vpc-peering.md

Customers finds hard to identify proper Cloud Manager service principal that needs to be authorised in remote subscription.
I have added a table that contains mappings between the Kyma Dashboard URL and Cloud Manager service principal.
Perhaps we should include BTP column in the mapping table as well.
Any feedback is welcome. 
- Added mapping table that lists service principals based on the Kyma dashboard URL.
- Removed dev as it is for internal use only.

docs: Adds Cloud Manager service principal to Kyma landscape mapping

---

docs/user/resources/04-70-10-aws-vpc-peering.md

Description
Customers finds hard to identify proper Cloud Manager principal that needs to be authorised in remote account.
I have added a table that contains mappings between BTP Cockpit URL, Kyma Dashboard URL, and Cloud Manager principal.
- Added mapping table that lists principals based on the Kyma dashboard URL.
- Removed dev as it is for internal use only.

docs: Adds Cloud Manager principal to Kyma landscape mapping

---

pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
pkg/kcp/provider/aws/vpcpeering/kcpNetworkLocalLoad.go
pkg/kcp/provider/aws/vpcpeering/kcpNetworkRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/kcpNetworkLocalLoad.go
pkg/kcp/provider/azure/vpcpeering/kcpNetworkRemoteLoad.go

- fixes the issue with deleting VPC peering when remote or local network is in Warning state

fix: unable to delete VPC peering when network is in Warning state

---

internal/controller/cloud-control/redisinstance_azure_test.go
pkg/kcp/provider/azure/mock/privateEndPointStore.go
pkg/kcp/provider/azure/redisinstance/createPrivateEndPoint.go
pkg/kcp/provider/azure/redisinstance/loadPrivateEndPoint.go
pkg/kcp/provider/azure/redisinstance/new.go
pkg/kcp/provider/azure/redisinstance/waitPrivateEndPointAvailable.go

- If PrivateEndPoint is loaded but in "Failed" state, try to update it. Intention is to fix the use case when PEP do not suceed to connect to Redis instance (long running exception from Azure side).

fix(AzureRedis): retry creating/updating private end point when it is in failed state

---

internal/controller/cloud-control/vpcpeering_aws_test.go
pkg/kcp/provider/aws/util/peering.go
pkg/kcp/provider/aws/vpcpeering/createRemoteClient.go
pkg/kcp/provider/aws/vpcpeering/createRemoteRoutes.go
pkg/kcp/provider/aws/vpcpeering/createRoutes.go
pkg/kcp/provider/aws/vpcpeering/createVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/deleteRoutes.go
pkg/kcp/provider/aws/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/new.go
pkg/kcp/provider/aws/vpcpeering/remotePeeringDelete.go
pkg/kcp/provider/aws/vpcpeering/remoteRoutesDelete.go
pkg/kcp/provider/aws/vpcpeering/waitPendingAcceptance.go
pkg/kcp/provider/aws/vpcpeering/waitVpcPeeringActive.go

According to AWS VPC Peering lifecycle VPC peering connection can only be accepted in certain stages.
- fixes accepting connection reconciliation loop
- fixes deletion of connection that is in one of the terminating statuses

fix(AwsVpcPeering): waits pending acceptance status before accepting connection

---

pkg/kcp/provider/aws/vpcpeering/loadRemoteRouteTables.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpc.go
pkg/kcp/provider/aws/vpcpeering/loadRemoteVpcPeeringConnection.go
pkg/kcp/provider/aws/vpcpeering/remotePeeringDelete.go

This is the fix for the AwsVpcPeering deletion issue when Cloud Manager permissions are removed from remote account after VPC peering connection was already established. 
Steps to reproduce this issue would be:
- Assign appropriate Cloud Manager permissions in remote account
- Create AwsVpcPeering and wait to become Ready
- Remove the Cloud Manager permissions from remote account
- Delete AwsVpcPeering and observe that it doesn't get deleted.
- fixes deletion issues when role is unauthorized

fix(AwsVpcPeering): fixes deletion issues when role is unauthorized

---

internal/controller/cloud-control/network_reference_test.go
internal/controller/cloud-control/scope_aws_test.go
pkg/common/actions/focal/loadKyma.go
pkg/common/actions/focal/loadScopeFromRef.go
pkg/common/actions/focal/new.go
pkg/common/actions/focal/state.go
pkg/kcp/network/handleNetworkReference.go
pkg/kcp/network/logLogicalErrorOnManagedNetworkMissing.go
pkg/kcp/network/reconciler.go
pkg/kcp/scope/kymaNetworkReferenceCreate.go
pkg/kcp/scope/kymaNetworkReferenceDelete.go
pkg/kcp/scope/reconciler.go
pkg/kcp/scope/scopeCreate.go
pkg/kcp/scope/scopeDelete.go
pkg/kcp/scope/scopeSave.go
pkg/kcp/scope/skrDeactivate.go

Issue #853 
- added to the KCP Network reconciler a step that will delete the KCP Network if Scope does not exist
- added to the KCP Scope reconciler a step that will delete the KCP Network
- refactored in the KCP Scope reconciler out of the `skrDeactivate` a part that deletes Scope into own separate action `scopeDelete`
- renamed in the KCP Scope w/out changes:
- `createKymaNetworkReference` to `kymaNetworkReferenceCreate`
- `createScope` to `scopeCreate`
- `saveScope` to `scopeSave`

fix: kcp kyma network delete

---

pkg/skr/gcpnfsvolume/reconciler.go
pkg/skr/gcpnfsvolume/validateSpec.go
pkg/skr/gcpnfsvolume/validateSpec_test.go

- remove obsolete methods `validateCapacity` and `validateFileShareName`
- validation was moved to API level with this PR https://github.com/kyma-project/cloud-manager/pull/791

refactor(GcpNfsVolume): remove obsolete methods validateCapacity and validateFileShareName

---

pkg/kcp/provider/aws/redisinstance/createElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/updateElastiCacheCluster.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheAvailable.go
pkg/kcp/provider/aws/redisinstance/waitElastiCacheDeleted.go
pkg/kcp/provider/aws/redisinstance/waitUserGroupDeleted.go
pkg/kcp/provider/gcp/redisinstance/createRedis.go
pkg/kcp/provider/gcp/redisinstance/deleteRedis.go
pkg/kcp/provider/gcp/redisinstance/loadRedis.go
pkg/kcp/provider/gcp/redisinstance/new.go
pkg/kcp/provider/gcp/redisinstance/updateRedis.go
pkg/kcp/provider/gcp/redisinstance/waitRedisAvailable.go
pkg/kcp/provider/gcp/redisinstance/waitRedisDeleted.go

chore(RedisInstance): no longer put cloud provider errors in conditions

---

api/cloud-resources/v1beta1/gcpredisinstance_types.go
api/cloud-resources/v1beta1/redisinstance_authsecret.go

- ...
- ...
- ...
https://github.com/kyma-project/cloud-manager/issues/881

refactor(RedisInstance): move auth secret to separate file

---

pkg/kcp/provider/azure/vpcpeering/deleteVpcPeering.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalLoad.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteDelete.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/remoteClientCreate.go
pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/waitNetworkTag.go

- Unify log message style for Azure VpcPeering reconciler

chore(AzureVpcPeering): improve log messages

---

pkg/feature/init.go
pkg/testinfra/run.go

- remove fallback value if envtest version is not defined
- application will panic if envtest version is not defined
- remove fallback if featureconfig is not defined
- featureflag init will return an error when featureconfig cannot be resolved.

chore: remove fallbacks (featureconfig, envtest)

---

.github/workflows/pr-checks.yml
cmd/main.go
config/featureToggles/featureToggles.yaml
internal/controller/cloud-control/nuke_aws_test.go
internal/controller/cloud-control/nuke_controller.go
internal/controller/cloud-control/suite_test.go
pkg/feature/ffNukeBackupsAws.go
pkg/kcp/nuke/reconciler.go
pkg/kcp/provider/aws/nuke/checkIfAllProviderResourcesDeleted.go
pkg/kcp/provider/aws/nuke/client/client.go
pkg/kcp/provider/aws/nuke/client/mock.go
pkg/kcp/provider/aws/nuke/createAwsClient.go
pkg/kcp/provider/aws/nuke/deleteNfsBackups.go
pkg/kcp/provider/aws/nuke/loadNfsBackups.go
pkg/kcp/provider/aws/nuke/new.go
pkg/kcp/provider/aws/nuke/providerResourceStatusDeleted.go
pkg/kcp/provider/aws/nuke/providerResourceStatusDeleting.go
pkg/kcp/provider/aws/nuke/providerResourceStatusDiscovered.go
pkg/kcp/provider/aws/nuke/state.go
pkg/skr/awsnfsvolumebackup/client/client.go
pkg/skr/awsnfsvolumebackup/client/mock.go

- Aws Client for listing and deleting the Recovery points
- Nuke reconciler components to delete recovery points.
Part of #863

feat(Nuke): Clean up of AWS Recovery Points when SKR is deleted

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/meta/metadata.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteCreate.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go
pkg/kcp/provider/azure/vpcpeering/vpcRemoteLoad.go

- handles Azure error InvalidAuthenticationTokenTenant and hides API error from the user
#892

fix(AzureVpcPeering): handles Azure error InvalidAuthenticationTokenTenant

---

internal/controller/cloud-control/vpcpeering_azure_test.go
pkg/kcp/provider/azure/vpcpeering/peeringLocalWaitReady.go

- skip status update while waiting local peering connected
Related issues: #896

chore(AzureVpcPeering): skip status update while waiting local peering connected

---

pkg/skr/runtime/manager/manager.go

- Skip SKR controller name validation added in https://github.com/kubernetes-sigs/controller-runtime/blob/v0.19.3/pkg/controller/controller.go#L154

fix: skip SKR controller name validation

---

pkg/kcp/nuke/reconciler.go

- use `focal.NewWithOptionalScope()` so that case when there's no Scope is gracefully handled

fix: nuke does not requeue when no scope

---

cmd/main.go
pkg/skr/runtime/looper/cyclicQueue.go
pkg/skr/runtime/looper/skrLooper.go
pkg/util/logFilterSink.go

- wrapped zap log sink with our custom filter messages sink to eliminate certain log entries produced by controller-runtime
- fixed cyclicQueue to return shuttingDown from Get when shut down
- fixed SkrLooper to recognize context DeadlineExceeded and Canceled errors and not log them

chore: dont log controller-runtime starting/stopping logs

---

pkg/composed/bridge.go
pkg/kcp/scope/addKymaFinalizer.go
pkg/kcp/scope/reconciler.go

+ prevent overwhelming reconciler outcome log entries when Scope did nothing
- Scope reconciler do not add finalizer when Kyma has deletionTimestamp to prevent error message `Kyma.operator.kyma-project.io "xxxx" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"cloud-control.kyma-project.io/deletion-hook"}`
- do not log Scope reconciler outcome to avoid majority of produced logs when Scope did nothing due to frequent KLM changes to Kyma

fix: Scope finalizer do not add finalizer to Kyma being deleted

---

pkg/kcp/provider/azure/redisinstance/updateStatus.go

- Do not update status if state had not changed (side effect of previous behavior is endless reconciliation).

Fix(AzureRedis): Do not update status if state has not changed

---

pkg/skr/backupschedule/evaluateNextRun_test.go

- Fix for occasional failure of test evaluateNextRun.TestWhenNextRunTimeIsNotDueYet()
Fixes #988

fix(BackupSchedule): flaky test

---

docs/user/resources/04-30-10-aws-vpc-peering.md
docs/user/resources/04-30-30-azure-vpc-peering.md
docs/user/tutorials/01-30-10-aws-vpc-peering.md
docs/user/tutorials/01-30-30-azure-vpc-peering.md

Updates tutorials with links to Cloud Manager principals that should be used depending on the Kyma landscape.

docs(VpcPeering): improve tutorial to identify correct principals

---

pkg/kcp/provider/aws/nuke/loadNfsBackups.go
pkg/kcp/provider/aws/nuke/loadVault.go
pkg/kcp/provider/aws/nuke/new.go
pkg/kcp/provider/aws/nuke/state.go

- Fix for preventing Nuke status going to error when no AwsNfsBackup exists
Fixes #https://github.tools.sap/kyma/cloud-manager-infra/issues/13

fix(NukeAwsBackups) - Load vault before listing the backups

---

.github/workflows/create-release-notes.yaml

Trigger "generate release notes" on non-patch tag name only, eg 1.2.0 will trigger it, but 1.2.1 will not.

chore: trigger generate release notes on non-patch version only

---

cmd/cli/README.md
cmd/cli/cmdGardenShootCreateAws.go
cmd/cli/cmdGardenShootCreateAzure.go
tools/dev/README.md

- adds ShootSpec.cloudProfileName since it is required filed
- updates interal dev docs

chore(cli): ShootSpec.CloudProfileName is required

---

pkg/skr/gcpnfsvolume/modifyPersistentVolumeClaim.go
pkg/skr/gcpnfsvolume/modifyPersistentVolumeClaim_test.go

Value in .Spec.Resources.Requests[storage] is no longer edited
- ...
- ...
- ...

fix(GcpNfsVolume): no longer tries to edit capacity in spec

---

pkg/kcp/provider/gcp/client/serviceUsageClient.go
pkg/kcp/provider/gcp/iprange/client/computeClient.go
pkg/kcp/provider/gcp/iprange/client/serviceNetworkingClient.go
pkg/kcp/provider/gcp/iprange/v2/checkGcpOperation.go
pkg/kcp/provider/gcp/iprange/v2/identifyPeeringIpRanges.go
pkg/kcp/provider/gcp/iprange/v2/loadPsaConnection.go
pkg/kcp/provider/gcp/iprange/v2/syncPsaConnection.go
pkg/kcp/provider/gcp/nfsbackup/client/fileBackupClient.go
pkg/kcp/provider/gcp/nfsinstance/checkGcpOperation.go
pkg/kcp/provider/gcp/nfsinstance/client/filestoreClient.go
pkg/kcp/provider/gcp/nfsinstance/loadNfsInstance.go
pkg/skr/backupschedule/loadBackups.go
pkg/skr/backupschedule/loadSource.go
pkg/skr/backupschedule/validateSchedule.go
pkg/skr/gcpnfsvolumebackup/checkBackupOperation.go
pkg/skr/gcpnfsvolumebackup/createNfsBackup.go
pkg/skr/gcpnfsvolumebackup/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go
pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolume.go
pkg/skr/gcpnfsvolumerestore/loadGcpNfsVolumeBackup.go

- Removing .V(x) in log messages to be consistent
- Adding/Enhancing log messages for Gcp Nfs volume/backup/restore
Fixes https://github.tools.sap/kyma/cloud-manager-infra/issues/21

fix: enhance the log messages of Gcp Nfs Volume/Backup/Restore

---

api/cloud-resources/v1beta1/condition.go
api/cloud-resources/v1beta1/gcpnfsvolumebackup_types.go
api/cloud-resources/v1beta1/state.go
pkg/skr/awsnfsvolumebackup/markFailed.go
pkg/skr/awsnfsvolumebackup/markFailed_test.go
pkg/skr/awsnfsvolumebackup/reconciler.go
pkg/skr/awsnfsvolumebackup/shortCircuit.go
pkg/skr/awsnfsvolumebackup/shortCircuit_test.go
pkg/skr/awsnfsvolumebackup/state_test.go
pkg/skr/gcpnfsvolumebackup/markFailed.go
pkg/skr/gcpnfsvolumebackup/markFailed_test.go
pkg/skr/gcpnfsvolumebackup/reconciler.go
pkg/skr/gcpnfsvolumebackup/shortCircuit.go
pkg/skr/gcpnfsvolumebackup/shortCircuit_test.go

- Short circuiting reconciliation loop if status is Ready or Failed.
- Mark the status to failed if a new backup exists.
Part of #https://github.tools.sap/kyma/cloud-manager-infra/issues/28

fix(NfsVolumeBackup): Short circuit reconciliation loop if completed

---

docs/user/00-30-vpc-peering.md

- Added Azure limitation for VPC peering

docs: Add Azure limitation for VPC peering

---

internal/controller/cloud-resources/aws/awsnfsvolumerestore_test.go
internal/controller/cloud-resources/gcpnfsvolumerestore_test.go
pkg/testinfra/dsl/conditions.go

- As restore can get deleted pretty fast, changing the integration tests to be more resilient in delete scenario
- ...
- ...

test: fix restore delete scenario in gcp/aws integration tests

---

api/cloud-resources/v1beta1/azurerwxvolumerestore_types.go
pkg/skr/azurerwxvolumerestore/startAzureRestore.go

- Fixing RecoveryPointId value passed to azure api
- Better error handling in startAzureRestore
See also #964

fix: AzureRwxVolumeRestore startAzureRestore logic

---

pkg/skr/azurerwxvolumerestore/checkRestoreJob.go
pkg/skr/azurerwxvolumerestore/findAzureRestoreJob.go
pkg/skr/azurerwxvolumerestore/loadAzureRwxVolumeBackup.go
pkg/skr/azurerwxvolumerestore/loadPersistentVolume.go
pkg/skr/azurerwxvolumerestore/loadPersistentVolumeClaim.go
pkg/skr/azurerwxvolumerestore/startAzureRestore.go

- removing unnecessary ErrorLogMsg calls during update status. Default behavior is sufficient.
- removing incorrect SuccessLogMsg calls during update status.
See also #964

fix: AzureRwxVolumeRestore updateStatus error messages

---

pkg/kcp/provider/azure/mock/storageStore.go
pkg/skr/azurerwxvolumebackup/client/constants.go
pkg/skr/azurerwxvolumebackup/client/jobs.go
pkg/skr/azurerwxvolumebackup/client/jobsMock.go
pkg/skr/azurerwxvolumebackup/client/restoreMock.go
pkg/skr/common/leases/lease.go

- Adding a method to find the backup job with the latest timestamp
- Adding a method to find the single backup job after the last backup
Utilizing both these methods provides a way to get the backup jobId after a successful trigger.
See also #963

feat: adding client methods for finding azure backup job ids

---

sec-scanners-config.yaml

- remove 1.2.4 from scanned images as 1.2.5 is already in prod. 1.2.4 has outdated x-crypto and x-net

fix: Update sec-scanners-config.yaml -remove 1.2.4 from scanned images

---

cmd/main.go
internal/controller/cloud-control/gcprediscluster_controller.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/rediscluster/client/memorystoreClusterClient.go
pkg/kcp/provider/gcp/rediscluster/state.go

- refactor GcpRedisCluster to use gcpclient.GcpClientProvider 
- refactor networkconnectivityclient to use custom token provider

refactor(cloud-control): use gcpclient.GcpClientProvider in GcpRedisCluster

---

pkg/kcp/provider/gcp/client/gcpClients.go

Before change, no issues were detected, as compute auth scope provider is superset of networkconnectivity auth scope
- ...
- ...
- ...

fix: change default auth scope provider for networkconnectivity gcpclient

---

cmd/main.go
internal/controller/cloud-control/redisinstance_controller.go
pkg/kcp/provider/gcp/client/gcpClients.go
pkg/kcp/provider/gcp/mock/server.go
pkg/kcp/provider/gcp/mock/type.go
pkg/kcp/provider/gcp/redisinstance/client/memorystoreClient.go
pkg/kcp/provider/gcp/redisinstance/state.go

refactor(cloud-control): use gcpclient.GcpClientProvider in GcpRedisInstance

---

pkg/kcp/provider/azure/vpcpeering/new.go
pkg/kcp/provider/azure/vpcpeering/peeringRemoteLoad.go

- stop and forget if loaded remote peering does not target kyma network
- #1256

feat(AzureVpcPeering): fixes the issue where peering connection hangs in Initiated state

---

pkg/skr/gcpnfsvolume/updateStatus.go

- Fix for updating the State to `Ready` after resizing the nfs volume size.
Fixes #1277

fix(GcpNfsVolume): Status not changing to Ready from Updating

---

Dockerfile

According to https://github.com/kyma-project/test-infra/tree/main/cmd/image-builder#cross-compiling-and-caching-for-non-native-architecture-builds to use benefit of cross-compilation it's required to ensure builder stage will run on native build platform.
- Add `--platform=$BUILDPLATFORM` to ensure builder stage runs on native build platform to cross-compile binary for arm64.

chore: lower docker build time

---

pkg/composed/bridge.go
pkg/config/binding.go
pkg/config/config_bind_test.go
pkg/config/testdata/file-v1.yaml
pkg/kcp/provider/gcp/client/gcpConfig_test.go
pkg/kcp/provider/gcp/client/gcpConstants.go

- fixed default value for `capacityCheckInterval`
- changed `gcp.client.GetDuration()` to return `GcpApiTimeout` in case given duration is zero or less
- added test for GcpConfig
- changed config so it parse non-strings like ints, floats, duration, slice... 
- changed `composed.Handle()` not to allow zero requeue delay, but to switch it to 1h instead

fix: gcpConfig 

---

docs/user/tutorials/01-30-30-azure-vpc-peering.md

- Identification of service principal moved from step 4 to step 2

docs(AzureVpcPeering): service principal needs to be identified in earlier steps

---

pkg/kcp/provider/aws/meta/metadata.go
pkg/kcp/provider/aws/meta/metadata_test.go
pkg/kcp/provider/aws/mock/vpcStore.go

- `IsNotFound` changed to detect `ResponseError`
- mocks modifeid reflect changes
- tests
Fixes #1431

fix(AwsVpcPeering): fixes IsNotFound to recognize HTTP 404

---

pkg/kcp/provider/azure/exposedData/vnetLoad.go

- pass `ResourceGroup` instead of `ResourceName` to `GetNetwork(ctx context.Context, resourceGroupName, virtualNetworkName string) (*armnetwork.VirtualNetwork, error)` method.
- in practice, resourceName and resourceGroupName are same, and that's why there were no issues. But that is just an implementation detail, and we should not rely on it.

fix: Azure vnetLoad use resourceGroupName instead of resourceName
